//! ph2d-panel-registry-init — append-only point of contact for
//! panel registration.
//!
//! ADR-0029 Phase D closed the migration: every in-tree panel
//! (Inspector / Hierarchy / Widget Gallery / Grid Snap) lives in
//! `ph2d_editor_core::panel::PANEL_REGISTRY` as a typed
//! `Panel<State>`. The legacy fn-pointer registry was deleted in
//! Phase D — this crate installs only the typed registry. Hosts call
//! it once at boot before `HeroScreen::new`.
//!
//! ## Cargo features
//!
//! - `default = ["panel-widget-gallery", "panel-hierarchy",
//!   "panel-inspector", "panel-grid-snap"]` — bundles every panel.
//! - `--no-default-features` — empty registry.
//! - `--no-default-features --features panel-inspector` — only the
//!   typed Inspector; chrome only otherwise.

#![forbid(unsafe_code)]

use ph2d_editor_core::panel::{ErasedPanel, install_panel_registry};

/// Aggregate the cargo-feature-gated panel manifests + install them
/// into the process-wide typed registry. Idempotent.
///
/// Returns `true` on first install, `false` if a registry was already
/// installed (matches `OnceLock::set` semantics).
pub fn register_all_panels() -> bool {
    install_panel_registry(build_typed_registry())
}

/// Build the typed `Panel<State>` registry without installing it.
///
/// The push block is regenerated by `cargo run -p ph2d-panel-sync` from
/// a scan of `crates/ph2d-panel-*`. Do NOT edit between the markers by
/// hand — staleness gate catches drift.
pub fn build_typed_registry() -> ph2d_editor_core::panel::PanelRegistry {
    #[allow(unused_mut)]
    let mut reg = ph2d_editor_core::panel::PanelRegistry::new_empty();
    // <ph2d-panel-sync:begin>
    #[cfg(feature = "panel-audio-editor")]
    reg.push(ErasedPanel::new::<ph2d_panel_audio_editor::AudioEditorPanel>());
    #[cfg(feature = "panel-audio-mixer")]
    reg.push(ErasedPanel::new::<ph2d_panel_audio_mixer::AudioMixerPanel>());
    #[cfg(feature = "panel-bgremoval")]
    reg.push(ErasedPanel::new::<ph2d_panel_bgremoval::BgRemovalPanel>());
    #[cfg(feature = "panel-color-equalization")]
    reg.push(ErasedPanel::new::<
        ph2d_panel_color_equalization::ColorEqualizationPanel,
    >());
    #[cfg(feature = "panel-equalize-sizes")]
    reg.push(ErasedPanel::new::<
        ph2d_panel_equalize_sizes::EqualizeSizesPanel,
    >());
    #[cfg(feature = "panel-flip")]
    reg.push(ErasedPanel::new::<ph2d_panel_flip::FlipPanel>());
    #[cfg(feature = "panel-grid-snap")]
    reg.push(ErasedPanel::new::<ph2d_panel_grid_snap::GridSnapPanel>());
    #[cfg(feature = "panel-hierarchy")]
    reg.push(ErasedPanel::new::<ph2d_panel_hierarchy::HierarchyPanel>());
    #[cfg(feature = "panel-inspector")]
    reg.push(ErasedPanel::new::<ph2d_panel_inspector::InspectorPanel>());
    #[cfg(feature = "panel-motion-graph")]
    reg.push(ErasedPanel::new::<ph2d_panel_motion_graph::MotionGraphPanel>());
    #[cfg(feature = "panel-motion-params")]
    reg.push(ErasedPanel::new::<
        ph2d_panel_motion_params::MotionParamsPanel,
    >());
    #[cfg(feature = "panel-padding")]
    reg.push(ErasedPanel::new::<ph2d_panel_padding::PaddingPanel>());
    #[cfg(feature = "panel-painter-layers")]
    reg.push(ErasedPanel::new::<
        ph2d_panel_painter_layers::PainterLayersPanel,
    >());
    #[cfg(feature = "panel-timeline")]
    reg.push(ErasedPanel::new::<ph2d_panel_timeline::TimelinePanel>());
    #[cfg(feature = "panel-upscale")]
    reg.push(ErasedPanel::new::<ph2d_panel_upscale::UpscalePanel>());
    #[cfg(feature = "panel-vector")]
    reg.push(ErasedPanel::new::<ph2d_panel_vector::VectorPanel>());
    #[cfg(feature = "panel-widget-gallery")]
    reg.push(ErasedPanel::new::<
        ph2d_panel_widget_gallery::WidgetGalleryPanel,
    >());
    // <ph2d-panel-sync:end>
    reg
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Expected typed panel count (Inspector + Hierarchy + Widget
    /// Gallery + Grid Snap after Phase C.4).
    const EXPECTED_TYPED: usize = {
        let mut n = 0;
        #[cfg(feature = "panel-audio-mixer")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-audio-editor")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-bgremoval")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-color-equalization")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-equalize-sizes")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-padding")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-vector")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-flip")]
        {
            n += 1;
        }
        // Hand-maintained mirror of build_typed_registry's sync-generated
        // push block — ph2d-panel-sync does NOT regenerate this const, so a
        // new panel feature must be counted here too (else workspace feature
        // unification enables the panel and this count drifts; cf. memory
        // feedback-fanout-registry-init-friction).
        #[cfg(feature = "panel-painter-layers")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-timeline")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-upscale")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-inspector")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-motion-graph")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-motion-params")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-hierarchy")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-widget-gallery")]
        {
            n += 1;
        }
        #[cfg(feature = "panel-grid-snap")]
        {
            n += 1;
        }
        n
    };

    #[test]
    fn build_typed_registry_matches_enabled_features() {
        let typed = build_typed_registry();
        assert_eq!(typed.panels().len(), EXPECTED_TYPED);
    }
}
