#![forbid(unsafe_code)]
//! ph2d-tool-registry-init — tool registration aggregation point.
//!
//! [`register_all`] calls each `ph2d-tool-*` crate's `register`. The marked
//! region is GENERATED by `cargo run -p ph2d-tool-sync` from a scan of
//! `crates/ph2d-tool-*` (ADR-0040 §2.3); the staleness gate
//! (`tests/staleness.rs`) fails CI if it drifts. Adding a tool = dropping a
//! crate + running the sync tool — never hand-editing this list. Same "drop a
//! crate, zero central edit" mechanism the node fan-out uses (`ph2d-node-sync`).
//! Called once at boot from `shells/<plat>/src/init.rs`.

use ph2d_tool_registry::Registry;

/// Register all tool manifests with the runtime registry. The body is
/// codegen'd (see module docs).
///
/// Order of calls doesn't matter for correctness — [`Registry::build`]
/// sorts by `(cluster, order, id)` for deterministic iteration (HR-5).
/// Alphabetical order in source is a merge-conflict-hygiene convention
/// (also gated by `architecture_register_all_alphabetical`); the sync
/// tool emits the scan sorted, so the two gates agree.
pub fn register_all(reg: &mut Registry) {
    // <ph2d-tool-sync:begin>
    ph2d_tool_bgremoval::register(reg);
    ph2d_tool_grid_snap::register(reg);
    ph2d_tool_make_square::register(reg);
    ph2d_tool_padding::register(reg);
    ph2d_tool_real_size::register(reg);
    ph2d_tool_trim_transparency::register(reg);
    // <ph2d-tool-sync:end>
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_all_wires_migrated_tools() {
        let mut reg = Registry::default();
        register_all(&mut reg);
        reg.build()
            .expect("registry should build cleanly with all wired tools");
        assert!(
            reg.by_id("make_square").is_some(),
            "make_square should be registered after PR 4"
        );
        assert!(
            reg.by_id("grid_snap").is_some(),
            "grid_snap should be registered after PR 6"
        );
        assert!(
            reg.by_id("bgremoval").is_some(),
            "bgremoval should be registered after PR 7"
        );
        assert!(
            reg.by_id("trim_transparency").is_some(),
            "trim_transparency should be registered after Wave 2 PR 11.4"
        );
    }

    #[test]
    fn image_tools_cluster_in_canonical_order() {
        // Wave 2 PR 11.4 contract: every Image Tools action pill comes
        // from the `image_tools` cluster, ordered by manifest
        // `order` field. `Registry::cluster` sorts by `(order, id)`,
        // so this is the canonical paint order: trim (40), make_square
        // (50), bgremoval (60), real_size (70), padding (80).
        let mut reg = Registry::default();
        register_all(&mut reg);
        reg.build().expect("registry should build");
        let cluster = reg.cluster("image_tools");
        let ids: Vec<&str> = cluster.iter().map(|m| m.id).collect();
        assert_eq!(
            ids,
            vec![
                "trim_transparency",
                "make_square",
                "bgremoval",
                "real_size",
                "padding"
            ]
        );
    }
}
