#![forbid(unsafe_code)]
//! ph2d-tool-registry-init — tool registration aggregation point.
//!
//! Two codegen'd entry points, both GENERATED by `cargo run -p ph2d-tool-sync`
//! from a scan of `crates/ph2d-tool-*` (ADR-0040); the staleness gate
//! (`tests/staleness.rs`) fails CI if either drifts. Adding a tool = dropping a
//! crate + running the sync — never hand-editing these lists. Same "drop a
//! crate, zero central edit" mechanism the node fan-out uses (`ph2d-node-sync`).
//!
//! - [`register_all`] — every tool with a `ToolManifest` (`pub fn register`),
//!   for the **data registry** (chrome pills / palette metadata).
//! - [`register_all_tools`] — every **modal/palette** tool (`pub fn make`),
//!   for the **behavior registry** ([`ToolRegistry`]) the shell switches.
//!
//! Both called once at boot from `shells/<plat>/src/init.rs`.

use ph2d_editor_core::tool::ToolRegistry;
use ph2d_tool_registry::Registry;

/// Register all tool manifests with the runtime registry. The body is
/// codegen'd (see module docs).
///
/// Order of calls doesn't matter for correctness — [`Registry::build`]
/// sorts by `(cluster, order, id)` for deterministic iteration (HR-5).
/// Alphabetical order in source is a merge-conflict-hygiene convention
/// (also gated by `architecture_register_all_alphabetical`); the sync
/// tool emits the scan sorted, so the two gates agree.
pub fn register_all(reg: &mut Registry) {
    // <ph2d-tool-sync:begin>
    ph2d_tool_bgremoval::register(reg);
    ph2d_tool_color_equalization::register(reg);
    ph2d_tool_equalize_sizes::register(reg);
    ph2d_tool_grid_snap::register(reg);
    ph2d_tool_make_square::register(reg);
    ph2d_tool_padding::register(reg);
    ph2d_tool_painter::register(reg);
    ph2d_tool_rasterize::register(reg);
    ph2d_tool_real_size::register(reg);
    ph2d_tool_trim_transparency::register(reg);
    ph2d_tool_upscale::register(reg);
    ph2d_tool_vector_direct::register(reg);
    ph2d_tool_vector_pen::register(reg);
    ph2d_tool_vector_pencil::register(reg);
    ph2d_tool_vector_select::register(reg);
    ph2d_tool_vector_shape::register(reg);
    // <ph2d-tool-sync:end>
}

/// Register every modal/palette tool's `Box<dyn Tool>` into the behavior
/// [`ToolRegistry`] the shell holds. The body is codegen'd (one
/// `reg.register(<crate>::make());` per tool crate exposing `pub fn make`).
/// The initial active tool is chosen by [`ToolRegistry::activate_default`]
/// (data-driven via `Tool::is_default`), NOT registration order — so the
/// codegen's alphabetical order does not decide the opening tool.
pub fn register_all_tools(reg: &mut ToolRegistry) {
    // <ph2d-tool-sync:tools:begin>
    reg.register(ph2d_tool_bgremoval::make());
    reg.register(ph2d_tool_brush::make());
    reg.register(ph2d_tool_color_equalization::make());
    reg.register(ph2d_tool_equalize_sizes::make());
    reg.register(ph2d_tool_move::make());
    reg.register(ph2d_tool_padding::make());
    reg.register(ph2d_tool_painter::make());
    reg.register(ph2d_tool_upscale::make());
    reg.register(ph2d_tool_vector_direct::make());
    reg.register(ph2d_tool_vector_pen::make());
    reg.register(ph2d_tool_vector_pencil::make());
    reg.register(ph2d_tool_vector_select::make());
    reg.register(ph2d_tool_vector_shape::make());
    // <ph2d-tool-sync:tools:end>
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_all_wires_migrated_tools() {
        let mut reg = Registry::default();
        register_all(&mut reg);
        reg.build()
            .expect("registry should build cleanly with all wired tools");
        assert!(
            reg.by_id("make_square").is_some(),
            "make_square should be registered after PR 4"
        );
        assert!(
            reg.by_id("grid_snap").is_some(),
            "grid_snap should be registered after PR 6"
        );
        assert!(
            reg.by_id("bgremoval").is_some(),
            "bgremoval should be registered after PR 7"
        );
        assert!(
            reg.by_id("trim_transparency").is_some(),
            "trim_transparency should be registered after Wave 2 PR 11.4"
        );
    }

    /// Wave 2 PR 11.4 contract: every Image Tools action pill comes
    /// from the `image_tools` cluster, ordered by manifest `order` field.
    /// `Registry::cluster` sorts by `(order, id)`, so this is the
    /// canonical paint order. The expected list is **codegen'd by
    /// `ph2d-tool-sync`** from `docs/design/tools/*.toml` (the same
    /// designer-canonical source `every_registered_manifest_has_matching_design_toml`
    /// validates against) — adding a new image_tools tool means dropping
    /// a design TOML + running `cargo run -p ph2d-tool-sync`; this test
    /// updates itself. The `#[rustfmt::skip]` keeps rustfmt from
    /// reformatting around the codegen markers.
    #[test]
    #[rustfmt::skip]
    fn image_tools_cluster_in_canonical_order() {
        let mut reg = Registry::default();
        register_all(&mut reg);
        reg.build().expect("registry should build");
        let cluster = reg.cluster("image_tools");
        let ids: Vec<&str> = cluster.iter().map(|m| m.id).collect();
        let expected: &[&str] = &[
        // <ph2d-tool-sync:image-tools-order:begin>
        "trim_transparency",
        "make_square",
        "bgremoval",
        "real_size",
        "padding",
        "color_equalization",
        "equalize_sizes",
        "rasterize",
        "upscale",
        "painter",
        // <ph2d-tool-sync:image-tools-order:end>
        ];
        assert_eq!(ids, expected);
    }
}
