#![forbid(unsafe_code)]
//! Aggregation point for node registration (ADR-0031).
//!
//! [`register_all_nodes`] calls each `ph2d-node-*` crate's `register`. The
//! marked region is GENERATED by `cargo run -p ph2d-node-sync` from a scan of
//! `crates/ph2d-node-*`; the staleness gate (`tests/staleness.rs`) fails CI if
//! it drifts. Adding a node = dropping a crate + running the sync tool — never
//! hand-editing this list. Called once at boot from the shell.

use ph2d_node_registry::{NodeRegistry, RegistryError};

/// Register every node crate's ops with the runtime registry. The body is
/// codegen'd (see module docs). Order is alphabetical by crate name (stable for
/// merges); registration order does not affect correctness — the registry keys
/// by id and iterates deterministically.
pub fn register_all_nodes(reg: &mut NodeRegistry) -> Result<(), RegistryError> {
    // <ph2d-node-sync:begin>
    ph2d_node_debug_const::register(reg)?;
    ph2d_node_debug_wave::register(reg)?;
    ph2d_node_force_attractor::register(reg)?;
    ph2d_node_force_curl::register(reg)?;
    ph2d_node_force_drag::register(reg)?;
    ph2d_node_force_vortex::register(reg)?;
    ph2d_node_force_wind::register(reg)?;
    ph2d_node_motion_bend::register(reg)?;
    ph2d_node_motion_clone::register(reg)?;
    ph2d_node_motion_drive::register(reg)?;
    ph2d_node_motion_emitter::register(reg)?;
    ph2d_node_motion_falloff::register(reg)?;
    ph2d_node_motion_fibonacci::register(reg)?;
    ph2d_node_motion_grid::register(reg)?;
    ph2d_node_motion_integrate::register(reg)?;
    ph2d_node_motion_look_at::register(reg)?;
    ph2d_node_motion_morph::register(reg)?;
    ph2d_node_motion_move::register(reg)?;
    ph2d_node_motion_noise::register(reg)?;
    ph2d_node_motion_orbit::register(reg)?;
    ph2d_node_motion_oscillator::register(reg)?;
    ph2d_node_motion_output::register(reg)?;
    ph2d_node_motion_rotate::register(reg)?;
    ph2d_node_motion_scale::register(reg)?;
    ph2d_node_motion_scatter::register(reg)?;
    ph2d_node_motion_spring::register(reg)?;
    ph2d_node_motion_stagger::register(reg)?;
    ph2d_node_motion_step::register(reg)?;
    ph2d_node_motion_strobe::register(reg)?;
    ph2d_node_motion_time_remap::register(reg)?;
    ph2d_node_motion_tint::register(reg)?;
    ph2d_node_motion_trail::register(reg)?;
    ph2d_node_motion_transform::register(reg)?;
    ph2d_node_motion_twist::register(reg)?;
    ph2d_node_motion_wiggle::register(reg)?;
    ph2d_node_pulse_beat::register(reg)?;
    ph2d_node_pulse_compare::register(reg)?;
    ph2d_node_pulse_counter::register(reg)?;
    ph2d_node_pulse_on_change::register(reg)?;
    ph2d_node_pulse_sample_hold::register(reg)?;
    ph2d_node_pulse_threshold::register(reg)?;
    ph2d_node_value_instance_field::register(reg)?;
    ph2d_node_value_lfo::register(reg)?;
    ph2d_node_value_map_range::register(reg)?;
    ph2d_node_value_math::register(reg)?;
    ph2d_node_value_switch::register(reg)?;
    // <ph2d-node-sync:end>
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_all_wires_without_collision() {
        let mut reg = NodeRegistry::new();
        register_all_nodes(&mut reg).expect("all node crates register cleanly");
        assert!(!reg.is_empty());
    }
}
