//! Per-corner **Fillet / Chamfer** for the Line polyline editor (the CAD corner gizmos: a CIRCLE handle
//! rounds the corner into a tangent arc, a SQUARE handle bevels it with a straight cut — Enio's photo).
//! Sibling of [`super::line`] so `line.rs` stays under the workspace file-LOC cap; pure geometry +
//! hit-testing, no `PaintState` access. Transcendental-free (HR-5): the fillet arc is generated by
//! recursive midpoint bisection (normalize the summed unit vectors — add + `sqrt`, never `sin`/`cos`),
//! and every angle test is a dot / cross of unit vectors.

/// How far out along the corner's OUTWARD bisector (× the grab tolerance) the two handles sit.
const HANDLE_GAP: f32 = 2.4;
/// Perpendicular straddle (× tol) so the circle (Fillet) + square (Chamfer) handles don't overlap.
const HANDLE_PERP: f32 = 1.3;
/// Max fillet tangent / chamfer distance as a fraction of the SHORTER adjacent edge (so adjacent corners
/// on a shared edge can't overrun each other too badly).
const MAX_FRAC: f32 = 0.45;
/// Fillet arc subdivision depth — `2^depth` segments (`3` → 8 segments / 9 points), plenty for a corner.
const ARC_DEPTH: u32 = 3;
/// Amounts below this (px) collapse the corner back to sharp (`None`).
pub(super) const MIN_AMOUNT: f32 = 0.5;

/// A per-corner modification: sharp (default), a tangent-arc **Fillet** (radius param = tangent distance),
/// or a straight **Chamfer** (param = cut distance along each edge). One or the other, never both.
#[derive(Clone, Copy, PartialEq, Debug)]
pub(super) enum CornerMod {
    None,
    Fillet(f32),
    Chamfer(f32),
}

impl CornerMod {
    /// Wire tag for the undo snapshot (`0` none, `1` fillet, `2` chamfer) + the amount.
    pub(super) fn to_wire(self) -> (u8, f32) {
        match self {
            CornerMod::None => (0, 0.0),
            CornerMod::Fillet(t) => (1, t),
            CornerMod::Chamfer(d) => (2, d),
        }
    }

    /// Rebuild from the undo wire tag (unknown tag → `None`).
    pub(super) fn from_wire((tag, amt): (u8, f32)) -> Self {
        match tag {
            1 => CornerMod::Fillet(amt),
            2 => CornerMod::Chamfer(amt),
            _ => CornerMod::None,
        }
    }
}

/// One corner's on-canvas gizmo for the shell overlay: the two handle positions (image px) + which mod is
/// active (`0` none, `1` fillet, `2` chamfer) so the shell can accent it.
pub struct LineCornerGizmo {
    /// The CIRCLE (Fillet) handle position.
    pub fillet_handle: [f32; 2],
    /// The SQUARE (Chamfer) handle position.
    pub chamfer_handle: [f32; 2],
    /// The active mod: `0` sharp, `1` fillet, `2` chamfer (drives the accent).
    pub active: u8,
}

/// A corner's local frame: `(vertex, dir_to_prev, dir_to_next, outward_bisector)`, all unit vectors bar
/// the vertex.
type CornerFrame = ([f32; 2], [f32; 2], [f32; 2], [f32; 2]);

/// The corner frame at index `i`: the vertex + the two OUTGOING unit edge directions (`a` toward the
/// previous point, `b` toward the next) + the OUTWARD bisector unit vector. `None` when `i` is not a real
/// interior corner (an endpoint of an open polyline, too few points, or a straight pass-through).
fn corner_frame(points: &[[f32; 2]], closed: bool, i: usize) -> Option<CornerFrame> {
    let n = points.len();
    if n < 3 {
        return None;
    }
    let is_corner = closed || (i > 0 && i < n - 1);
    if !is_corner {
        return None;
    }
    let v = points[i];
    let pi = if closed { (i + n - 1) % n } else { i - 1 };
    let ni = if closed { (i + 1) % n } else { i + 1 };
    let a = norm(sub(points[pi], v))?;
    let b = norm(sub(points[ni], v))?;
    let bis = add(a, b);
    let blen = len(bis);
    if blen < 1e-3 {
        return None; // straight (a ≈ -b) — no corner to round
    }
    let n_out = [-bis[0] / blen, -bis[1] / blen];
    Some((v, a, b, n_out))
}

/// The two handle positions (fillet-circle, chamfer-square) for corner `i`, or `None` when it is not a
/// real corner. Straddle the outward bisector so they sit side by side just outside the vertex.
pub(super) fn handle_positions(
    points: &[[f32; 2]],
    closed: bool,
    i: usize,
    tol: f32,
) -> Option<([f32; 2], [f32; 2])> {
    let (v, _a, _b, n_out) = corner_frame(points, closed, i)?;
    let perp = [-n_out[1], n_out[0]];
    let base = [
        v[0] + n_out[0] * tol * HANDLE_GAP,
        v[1] + n_out[1] * tol * HANDLE_GAP,
    ];
    let fillet = [
        base[0] + perp[0] * tol * HANDLE_PERP,
        base[1] + perp[1] * tol * HANDLE_PERP,
    ];
    let chamfer = [
        base[0] - perp[0] * tol * HANDLE_PERP,
        base[1] - perp[1] * tol * HANDLE_PERP,
    ];
    Some((fillet, chamfer))
}

/// Hit-test every corner's two handles at `pos`; return `(corner_index, is_fillet)` for the first within
/// `tol`, else `None`. Fillet (circle) wins a tie with its own chamfer (checked first).
pub(super) fn hit_handle(
    points: &[[f32; 2]],
    closed: bool,
    pos: [f32; 2],
    tol: f32,
) -> Option<(usize, bool)> {
    let tol2 = tol * tol;
    for i in 0..points.len() {
        let Some((f, c)) = handle_positions(points, closed, i, tol) else {
            continue;
        };
        if dist2(f, pos) <= tol2 {
            return Some((i, true));
        }
        if dist2(c, pos) <= tol2 {
            return Some((i, false));
        }
    }
    None
}

/// The max fillet-tangent / chamfer distance for corner `i`: [`MAX_FRAC`] of the shorter adjacent edge.
fn max_amount(points: &[[f32; 2]], closed: bool, i: usize) -> f32 {
    let n = points.len();
    if corner_frame(points, closed, i).is_none() {
        return 0.0;
    }
    let v = points[i];
    let pi = if closed { (i + n - 1) % n } else { i - 1 };
    let ni = if closed { (i + 1) % n } else { i + 1 };
    let lp = len(sub(points[pi], v));
    let ln = len(sub(points[ni], v));
    MAX_FRAC * lp.min(ln)
}

/// The amount (tangent / chamfer distance) implied by dragging a corner `i` handle to `cursor`: the
/// outward-bisector projection of `cursor − vertex`, minus the handle gap, clamped to `[0, max]`.
pub(super) fn amount_from_cursor(
    points: &[[f32; 2]],
    closed: bool,
    i: usize,
    cursor: [f32; 2],
    tol: f32,
) -> f32 {
    let Some((v, _a, _b, n_out)) = corner_frame(points, closed, i) else {
        return 0.0;
    };
    let proj = dot(sub(cursor, v), n_out) - tol * HANDLE_GAP;
    proj.clamp(0.0, max_amount(points, closed, i))
}

/// Build the shell overlay gizmos (handle positions + active mod) for every real corner — empty while the
/// polyline is too short / all endpoints.
pub(super) fn gizmos(
    points: &[[f32; 2]],
    closed: bool,
    mods: &[CornerMod],
    tol: f32,
) -> Vec<LineCornerGizmo> {
    let mut out = Vec::new();
    for i in 0..points.len() {
        let Some((fillet, chamfer)) = handle_positions(points, closed, i, tol) else {
            continue;
        };
        let active = match mods.get(i).copied().unwrap_or(CornerMod::None) {
            CornerMod::Fillet(t) if t > MIN_AMOUNT => 1,
            CornerMod::Chamfer(d) if d > MIN_AMOUNT => 2,
            _ => 0,
        };
        out.push(LineCornerGizmo {
            fillet_handle: fillet,
            chamfer_handle: chamfer,
            active,
        });
    }
    out
}

/// Expand the polyline into its RENDERED path: each sharp corner passes through unchanged; a Fillet
/// replaces the vertex with a tangent arc; a Chamfer with a straight bevel (two points). Closes the loop
/// (re-appends the first rendered point) when `closed`. This is what the preview + bake consume.
pub(super) fn expand(
    points: &[[f32; 2]],
    closed: bool,
    mods: &[CornerMod],
    _tol: f32,
) -> Vec<[f32; 2]> {
    let n = points.len();
    if n < 2 {
        return points.to_vec();
    }
    let mut out = Vec::new();
    for i in 0..n {
        let m = mods.get(i).copied().unwrap_or(CornerMod::None);
        match (corner_frame(points, closed, i), m) {
            (Some((v, a, b, _)), CornerMod::Fillet(t)) if t > MIN_AMOUNT => {
                out.extend(fillet_points(v, a, b, t));
            }
            (Some((v, a, b, _)), CornerMod::Chamfer(d)) if d > MIN_AMOUNT => {
                out.push([v[0] + a[0] * d, v[1] + a[1] * d]);
                out.push([v[0] + b[0] * d, v[1] + b[1] * d]);
            }
            _ => out.push(points[i]),
        }
    }
    if closed && out.len() >= 3 {
        out.push(out[0]);
    }
    out
}

/// The fillet arc for a corner: tangent points `P0 = v + a·t`, `P1 = v + b·t`, and the tangent arc between
/// them (centre on the inward bisector). Returned as `[P0, …arc…, P1]`. Degenerates to `[P0, P1]` for a
/// near-straight corner. Centre maths: `L = t·|a+b| / (1 + a·b)` along the inward bisector — pure algebra.
fn fillet_points(v: [f32; 2], a: [f32; 2], b: [f32; 2], t: f32) -> Vec<[f32; 2]> {
    let p0 = [v[0] + a[0] * t, v[1] + a[1] * t];
    let p1 = [v[0] + b[0] * t, v[1] + b[1] * t];
    let apb = add(a, b);
    let apblen = len(apb);
    let abdot = dot(a, b);
    let denom = 1.0 + abdot;
    if apblen < 1e-3 || denom.abs() < 1e-4 {
        return vec![p0, p1];
    }
    let bis = [apb[0] / apblen, apb[1] / apblen]; // INWARD bisector (toward a+b)
    let l = t * apblen / denom;
    let c = [v[0] + bis[0] * l, v[1] + bis[1] * l];
    let r = len(sub(p0, c));
    if r < 1e-3 {
        return vec![p0, p1];
    }
    let u = [(p0[0] - c[0]) / r, (p0[1] - c[1]) / r];
    let w = [(p1[0] - c[0]) / r, (p1[1] - c[1]) / r];
    let mut pts = vec![p0];
    arc_bisect(c, r, u, w, ARC_DEPTH, &mut pts);
    pts
}

/// Append the arc from unit direction `u` to `w` (about centre `c`, radius `r`), EXCLUDING the `u`
/// endpoint, INCLUDING `w`. Midpoint bisection: the halfway direction is `normalize(u + w)` (no trig —
/// HR-5). At depth 0 it emits the single `w` endpoint.
fn arc_bisect(c: [f32; 2], r: f32, u: [f32; 2], w: [f32; 2], depth: u32, out: &mut Vec<[f32; 2]>) {
    if depth == 0 {
        out.push([c[0] + w[0] * r, c[1] + w[1] * r]);
        return;
    }
    let Some(mid) = norm(add(u, w)) else {
        // u ≈ -w (180°): can't bisect by summation — just emit the endpoint.
        out.push([c[0] + w[0] * r, c[1] + w[1] * r]);
        return;
    };
    arc_bisect(c, r, u, mid, depth - 1, out);
    arc_bisect(c, r, mid, w, depth - 1, out);
}

// ── tiny 2-vector helpers (local; the shape modules keep their own to stay decoupled) ──
fn sub(p: [f32; 2], q: [f32; 2]) -> [f32; 2] {
    [p[0] - q[0], p[1] - q[1]]
}
fn add(p: [f32; 2], q: [f32; 2]) -> [f32; 2] {
    [p[0] + q[0], p[1] + q[1]]
}
fn dot(p: [f32; 2], q: [f32; 2]) -> f32 {
    p[0] * q[0] + p[1] * q[1]
}
fn len(p: [f32; 2]) -> f32 {
    (p[0] * p[0] + p[1] * p[1]).sqrt()
}
fn norm(p: [f32; 2]) -> Option<[f32; 2]> {
    let l = len(p);
    if l < 1e-6 {
        None
    } else {
        Some([p[0] / l, p[1] / l])
    }
}
fn dist2(p: [f32; 2], q: [f32; 2]) -> f32 {
    let d = sub(p, q);
    d[0] * d[0] + d[1] * d[1]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chamfer_replaces_a_corner_with_two_bevel_points() {
        // Right-angle corner at (10,0): a→(0,0), b→(10,10). Chamfer 4 → bevel points 4 px down each edge.
        let pts = [[0.0, 0.0], [10.0, 0.0], [10.0, 10.0]];
        let mods = [CornerMod::None, CornerMod::Chamfer(4.0), CornerMod::None];
        let path = expand(&pts, false, &mods, 8.0);
        // endpoints kept + two bevel points instead of the sharp vertex.
        assert_eq!(path[0], [0.0, 0.0]);
        assert_eq!(*path.last().unwrap(), [10.0, 10.0]);
        assert_eq!(path[1], [6.0, 0.0], "4 px back along the incoming edge");
        assert_eq!(path[2], [10.0, 4.0], "4 px along the outgoing edge");
    }

    #[test]
    fn fillet_arc_stays_on_a_circle_tangent_to_both_edges() {
        // Same right-angle corner, fillet tangent 4. Every arc point is equidistant from the centre and
        // the tangent points sit 4 px along each edge; the arc bulges toward the interior (x<10).
        let v = [10.0, 0.0];
        let a = [-1.0, 0.0];
        let b = [0.0, 1.0];
        let arc = fillet_points(v, a, b, 4.0);
        assert_eq!(arc[0], [6.0, 0.0], "P0 = tangent on the incoming edge");
        assert_eq!(
            *arc.last().unwrap(),
            [10.0, 4.0],
            "P1 = tangent on the outgoing edge"
        );
        assert!(arc.len() >= 5, "the arc is subdivided, got {}", arc.len());
        // Centre of a 90° fillet with tangent 4 is at (6,4), radius 4 — check every point is on it.
        let c = [6.0, 4.0];
        for p in &arc {
            let r = ((p[0] - c[0]).powi(2) + (p[1] - c[1]).powi(2)).sqrt();
            assert!(
                (r - 4.0).abs() < 0.05,
                "point {p:?} off the r=4 arc (r={r})"
            );
        }
    }

    #[test]
    fn amount_clamps_to_the_shorter_edge() {
        // Corner 1 between a 10 px and a 30 px edge → max = 0.45 * 10 = 4.5, whatever the cursor.
        let pts = [[0.0, 0.0], [10.0, 0.0], [10.0, 30.0]];
        let far = amount_from_cursor(&pts, false, 1, [100.0, -100.0], 8.0);
        assert!(
            (far - 4.5).abs() < 1e-3,
            "clamped to 0.45*min edge, got {far}"
        );
    }
}
