//! As 24 linhas do painel e os cinco GRUPOS que as tornam legíveis.
//!
//! ⚠️ **Vinte e quatro números num painel plano é ilegível, e cortar knobs não é a
//! cura — o AGRUPAMENTO é.** Um lado sem as duas tangentes deixa de ser uma cúbica,
//! então nenhum destes é dispensável; o que se pode fazer é dizer **a que lado cada um
//! pertence**, e é isso que os cinco grupos fazem (`Corners` + um por aresta). A ordem
//! dentro de cada aresta é a de percurso: `In` é a tangente que sai do primeiro canto,
//! `Out` a que chega ao segundo.
//!
//! ⚠️ **A faixa é ±10 unidades de MUNDO, e ela é a do irmão `motion.four_point_warp`
//! por decisão e não por cópia:** os dois deformam a mesma caixa envolvente com a
//! mesma grandeza, e duas faixas diferentes fariam o mesmo arrasto significar coisas
//! diferentes conforme o nó — que é exactamente o que a folha 06 registou como
//! *"rótulo promete o que o modelo entrega"*.

use ph2d_node_registry::{ParamGroup, ParamUiHint, ParamWidget};

pub(crate) static PARAM_HINTS: &[ParamUiHint] = &[
    ParamUiHint {
        param: "tl_dx",
        label: "Top-Left X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "tl_dy",
        label: "Top-Left Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "tr_dx",
        label: "Top-Right X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "tr_dy",
        label: "Top-Right Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "br_dx",
        label: "Bottom-Right X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "br_dy",
        label: "Bottom-Right Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "bl_dx",
        label: "Bottom-Left X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "bl_dy",
        label: "Bottom-Left Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "top_a_dx",
        label: "In X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "top_a_dy",
        label: "In Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "top_b_dx",
        label: "Out X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "top_b_dy",
        label: "Out Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "right_a_dx",
        label: "In X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "right_a_dy",
        label: "In Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "right_b_dx",
        label: "Out X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "right_b_dy",
        label: "Out Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "bottom_a_dx",
        label: "In X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "bottom_a_dy",
        label: "In Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "bottom_b_dx",
        label: "Out X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "bottom_b_dy",
        label: "Out Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "left_a_dx",
        label: "In X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "left_a_dy",
        label: "In Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "left_b_dx",
        label: "Out X",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
    ParamUiHint {
        param: "left_b_dy",
        label: "Out Y",
        min: -10.0,
        max: 10.0,
        step: 0.01,
        widget: ParamWidget::Slider,
    },
];

pub(crate) static PARAM_GROUPS: &[ParamGroup] = &[
    ParamGroup::new("tl_dx", "Corners"),
    ParamGroup::new("tl_dy", "Corners"),
    ParamGroup::new("tr_dx", "Corners"),
    ParamGroup::new("tr_dy", "Corners"),
    ParamGroup::new("br_dx", "Corners"),
    ParamGroup::new("br_dy", "Corners"),
    ParamGroup::new("bl_dx", "Corners"),
    ParamGroup::new("bl_dy", "Corners"),
    ParamGroup::new("top_a_dx", "Top Edge"),
    ParamGroup::new("top_a_dy", "Top Edge"),
    ParamGroup::new("top_b_dx", "Top Edge"),
    ParamGroup::new("top_b_dy", "Top Edge"),
    ParamGroup::new("right_a_dx", "Right Edge"),
    ParamGroup::new("right_a_dy", "Right Edge"),
    ParamGroup::new("right_b_dx", "Right Edge"),
    ParamGroup::new("right_b_dy", "Right Edge"),
    ParamGroup::new("bottom_a_dx", "Bottom Edge"),
    ParamGroup::new("bottom_a_dy", "Bottom Edge"),
    ParamGroup::new("bottom_b_dx", "Bottom Edge"),
    ParamGroup::new("bottom_b_dy", "Bottom Edge"),
    ParamGroup::new("left_a_dx", "Left Edge"),
    ParamGroup::new("left_a_dy", "Left Edge"),
    ParamGroup::new("left_b_dx", "Left Edge"),
    ParamGroup::new("left_b_dy", "Left Edge"),
];
