#![forbid(unsafe_code)]
//! `ph2d-bindgen` — generates Luau type definitions + MCP JSON Schema
//! from the canonical [`ph2d_mcp::CATALOG`].
//!
//! Two outputs (HR-10 parity):
//! - `runtime/luau/ph2d.d.luau` — Luau type definitions consumed by
//!   luau-lsp for autocomplete + type-check inside `.luau` source.
//! - `runtime/mcp/schema.json` — MCP tool catalog in the JSON Schema
//!   format MCP clients (Claude editor) consume.
//!
//! ### Modes
//!
//! - `ph2d-bindgen --write` — regenerate and write to disk. Run this
//!   locally after editing `crates/ph2d-mcp/src/catalog.rs`.
//! - `ph2d-bindgen --check` — regenerate in memory, diff against the
//!   committed files, exit non-zero on drift. CI uses this to enforce
//!   parity (HR-10).
//! - `ph2d-bindgen` (no args) — same as `--check`.

use ph2d_mcp::CATALOG;
use std::path::{Path, PathBuf};

fn main() -> std::process::ExitCode {
    let mode = parse_mode();
    let root = workspace_root();
    let luau_path = root.join("runtime/luau/ph2d.d.luau");
    let schema_path = root.join("runtime/mcp/schema.json");

    let luau = generate_luau();
    let schema = generate_schema();

    match mode {
        Mode::Write => {
            ensure_parent(&luau_path);
            ensure_parent(&schema_path);
            std::fs::write(&luau_path, &luau).expect("write luau");
            std::fs::write(&schema_path, &schema).expect("write schema");
            println!("✓ wrote {}", luau_path.display());
            println!("✓ wrote {}", schema_path.display());
            std::process::ExitCode::SUCCESS
        }
        Mode::Check => {
            let mut drift = false;
            if drift_detected("luau", &luau_path, &luau) {
                drift = true;
            }
            if drift_detected("schema", &schema_path, &schema) {
                drift = true;
            }
            if drift {
                eprintln!(
                    "ph2d-bindgen --check: drift detected. Run `cargo run -p ph2d-bindgen -- --write` and commit."
                );
                std::process::ExitCode::FAILURE
            } else {
                println!("✓ generated artifacts match committed files (HR-10 parity OK)");
                std::process::ExitCode::SUCCESS
            }
        }
    }
}

#[derive(Copy, Clone, Debug)]
enum Mode {
    Check,
    Write,
}

fn parse_mode() -> Mode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.iter().any(|a| a == "--write") {
        Mode::Write
    } else {
        Mode::Check
    }
}

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR points at tools/ph2d-bindgen — go up two
    // levels to reach the workspace root regardless of where `cargo
    // run` was invoked from.
    let here = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    here.ancestors()
        .nth(2)
        .expect("workspace root above tools/ph2d-bindgen")
        .to_path_buf()
}

fn ensure_parent(p: &Path) {
    if let Some(parent) = p.parent() {
        std::fs::create_dir_all(parent).expect("create parent dir");
    }
}

fn drift_detected(label: &str, path: &Path, fresh: &str) -> bool {
    match std::fs::read_to_string(path) {
        Ok(committed) => {
            if committed == fresh {
                false
            } else {
                eprintln!(
                    "✗ {label} drift: committed != generated\n  committed: {}",
                    path.display()
                );
                true
            }
        }
        Err(_) => {
            eprintln!("✗ {label} missing: {} (run --write)", path.display());
            true
        }
    }
}

const GENERATED_BANNER_LUAU: &str = "\
-- ============================================================
-- AUTO-GENERATED by tools/ph2d-bindgen — DO NOT EDIT BY HAND.
--
-- Source of truth: crates/ph2d-mcp/src/catalog.rs
-- Regenerate:      cargo run -p ph2d-bindgen -- --write
-- HR-10 parity is enforced by CI; drift fails the build.
-- ============================================================

";

fn generate_luau() -> String {
    // Group tools by namespace prefix (everything before the first
    // dot). E.g. "scene.spawn_entity" → namespace "scene", member
    // "spawn_entity". Tools without a dot become top-level methods.
    use std::collections::BTreeMap;
    let mut by_ns: BTreeMap<&str, Vec<(&str, &str)>> = BTreeMap::new();
    for spec in CATALOG {
        let (ns, member) = spec.name.split_once('.').unwrap_or(("", spec.name));
        by_ns.entry(ns).or_default().push((member, spec.luau_signature));
    }
    // Sort members within each namespace for stable output.
    for v in by_ns.values_mut() {
        v.sort_by_key(|(m, _)| *m);
    }

    let mut out = String::new();
    out.push_str(GENERATED_BANNER_LUAU);
    out.push_str("export type Ph2d = {\n");
    for (ns, members) in &by_ns {
        if ns.is_empty() {
            for (member, sig) in members {
                let lua_typed = signature_to_luau_field(member, sig);
                out.push_str("    ");
                out.push_str(&lua_typed);
                out.push_str(",\n");
            }
        } else {
            out.push_str("    ");
            out.push_str(ns);
            out.push_str(": {\n");
            for (member, sig) in members {
                let lua_typed = signature_to_luau_field(member, sig);
                out.push_str("        ");
                out.push_str(&lua_typed);
                out.push_str(",\n");
            }
            out.push_str("    },\n");
        }
    }
    out.push_str("}\n\n");
    out.push_str("declare ph2d: Ph2d\n");
    out
}

/// Translate a [`ph2d_mcp::ToolSpec::luau_signature`] (which is
/// already in human form like `spawn_entity(): { entity: number }`)
/// into a Luau record-field declaration:
/// `spawn_entity: () -> { entity: number }`.
fn signature_to_luau_field(member: &str, sig: &str) -> String {
    // Find the parens and the colon-return.
    // Input: `name(arg: t, arg2: t2): return_t`
    // Output: `name: (arg: t, arg2: t2) -> return_t`
    let _ = member;
    if let Some(paren_open) = sig.find('(')
        && let Some(paren_close) = sig.find(')')
        && paren_close > paren_open
    {
        let name = &sig[..paren_open];
        let args = &sig[paren_open..=paren_close];
        let after = &sig[paren_close + 1..];
        let ret = after.trim_start_matches(':').trim();
        let ret_clause = if ret.is_empty() {
            String::new()
        } else {
            format!(" -> {ret}")
        };
        return format!("{name}: {args}{ret_clause}");
    }
    // Fallback: emit raw.
    sig.to_string()
}

fn generate_schema() -> String {
    let tools: Vec<serde_json::Value> = CATALOG
        .iter()
        .map(|spec| {
            let input: serde_json::Value =
                serde_json::from_str(spec.input_schema_json).expect("input_schema valid");
            let output: serde_json::Value =
                serde_json::from_str(spec.output_schema_json).expect("output_schema valid");
            let mut obj = serde_json::json!({
                "name": spec.name,
                "description": spec.description,
                "input_schema": input,
                "output_schema": output,
            });
            if spec.destructive {
                obj["destructive"] = serde_json::Value::Bool(true);
            }
            obj
        })
        .collect();
    let doc = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$generator": "tools/ph2d-bindgen",
        "$source_of_truth": "crates/ph2d-mcp/src/catalog.rs",
        "tools": tools,
    });
    let mut out = serde_json::to_string_pretty(&doc).expect("serialize schema");
    out.push('\n');
    out
}
