//! `ErasedPanel` — type-erased wrapper around `Panel<State>`.
//!
//! ADR-0029 §4.4. The registry guards `Vec<ErasedPanel>` (not
//! `&'static PanelManifest`). At install time, `ErasedPanel::new::<P>()`
//! creates a default `P::State` boxed; subsequent calls downcast
//! that box once per dispatch.
//!
//! The downcast is technically `dyn Any::downcast_mut` which panics
//! on type mismatch. By construction this never happens: the
//! manifest stores fn pointers that hard-code the `<P>` type-param,
//! and the state was created via the same `P` at install. A
//! mismatch would mean a corrupted manifest, which the type system
//! prevents.

use super::EventOutcome;
use super::PaintCtx;
use super::Panel;
use super::PanelHostInternal;
use super::PanelManifest;
use crate::interaction::{WidgetEvent, WidgetStore};
use std::any::Any;

/// One entry in the runtime panel registry. Holds the manifest
/// (fn pointers + identity) plus the panel's owned state as a
/// `Box<dyn Any>`. Methods downcast to the typed `P::State` via
/// the manifest's `state_type_check`.
pub struct ErasedPanel {
    pub manifest: PanelManifest,
    state: Box<dyn Any + Send>,
}

impl ErasedPanel {
    pub fn new<P: Panel>() -> Self {
        Self {
            manifest: PanelManifest::for_panel::<P>(),
            state: Box::new(<P::State>::default()),
        }
    }

    /// Dispatch the panel's paint via its manifest. The manifest's
    /// `paint_fn` receives `&mut dyn Any` and does the typed
    /// downcast internally (the fn is generated by `PanelManifest::
    /// for_panel::<P>` and knows the exact `P::State` type).
    pub fn paint(&mut self, ctx: &mut PaintCtx) {
        (self.manifest.paint_fn)(self.state.as_mut(), ctx);
    }

    /// Dispatch the panel's apply_event via its manifest.
    pub fn apply_event(
        &mut self,
        host: &mut dyn PanelHostInternal,
        ev: WidgetEvent,
    ) -> EventOutcome {
        (self.manifest.apply_event_fn)(self.state.as_mut(), host, ev)
    }

    /// Pre-register widget `NodeId`s. No state involved.
    pub fn populate(&self, store: &mut WidgetStore) {
        (self.manifest.populate_fn)(store);
    }
}
