//! `PanelManifest` — static identity + fn pointers describing one
//! panel. ADR-0029 §4.4.
//!
//! Built via [`PanelManifest::for_panel::<P>()`] which generates
//! type-erased fn pointers that internally downcast the state to
//! `P::State` and dispatch to `P::paint` / `P::apply_event`.
//! Panels never write fn pointers by hand.

use super::EventOutcome;
use super::PaintCtx;
use super::Panel;
use super::PanelHostInternal;
use crate::interaction::{WidgetEvent, WidgetStore};
use ph2d_a11y::NodeId;
use std::any::Any;

/// Type-erased fn pointer shapes used inside the manifest. State
/// flows as `&mut dyn Any`; the closures generated by
/// `for_panel::<P>` do the downcast to `P::State`.
pub type ErasedPaintFn = for<'a> fn(&mut dyn Any, &mut PaintCtx<'a>);
pub type ErasedApplyEventFn =
    fn(&mut dyn Any, &mut dyn PanelHostInternal, WidgetEvent) -> EventOutcome;
pub type PopulateFn = fn(&mut WidgetStore);

#[derive(Clone, Copy)]
pub struct PanelManifest {
    pub id: &'static str,
    pub panel_node_id: NodeId,
    pub default_visible: bool,
    pub paint_fn: ErasedPaintFn,
    pub apply_event_fn: ErasedApplyEventFn,
    pub populate_fn: PopulateFn,
}

impl PanelManifest {
    /// Construct a manifest for a specific `Panel` impl. Generates
    /// type-erased fn pointers that internally call the typed
    /// methods on `P` after downcasting the state.
    pub fn for_panel<P: Panel>() -> Self {
        Self {
            id: P::ID,
            panel_node_id: P::NODE_ID,
            default_visible: P::DEFAULT_VISIBLE,
            paint_fn: paint_dispatch::<P>,
            apply_event_fn: apply_event_dispatch::<P>,
            populate_fn: P::populate,
        }
    }
}

fn paint_dispatch<P: Panel>(state: &mut dyn Any, ctx: &mut PaintCtx) {
    let state = state
        .downcast_mut::<P::State>()
        .expect("ErasedPanel state type mismatch (paint_dispatch)");
    P::paint(state, ctx);
}

fn apply_event_dispatch<P: Panel>(
    state: &mut dyn Any,
    host: &mut dyn PanelHostInternal,
    ev: WidgetEvent,
) -> EventOutcome {
    let state = state
        .downcast_mut::<P::State>()
        .expect("ErasedPanel state type mismatch (apply_event_dispatch)");
    P::apply_event(state, host, ev)
}
