//! `panel_seam!` — declarative panel↔tool wiring for the **forwarder** family
//! (blindagem Fase 2).
//!
//! ## What it solves
//!
//! The "3 cycles per button" tax came from hand-wiring the same seam across
//! many sites: registering each widget in `populate.rs` AND forwarding each one
//! in `event.rs`. Forget a site and the widget is painted but silently dead.
//! Fase 0/1 made that *safe* (the `architecture_panel_wiring_parity` gate +
//! the behavioral seam tests catch it), but it was still tedious.
//!
//! For the **sabor-3 image-tool panel** shape — a thin forwarder whose
//! `apply_event` pushes `EditorAction::ToolPanelEvent` / `CancelActiveTool`
//! (Padding, BgRemoval, Color Equalization, Upscale, Equalize Sizes) — both
//! `populate` and `apply_event` are pure boilerplate derived from one list of
//! widgets. This macro generates BOTH from that single declaration, so a
//! registered widget CANNOT be missing its forward arm (and vice-versa): the
//! two are emitted together, by construction.
//!
//! ## What it does NOT cover (use hand-written `event.rs` for these)
//!
//! This macro is deliberately narrow — it is the forwarder shape only. Panels
//! that dispatch through other paths keep their explicit `event.rs`: grid-snap
//! (writes `GridSnapState` directly + indirect kind-option mapping table),
//! inspector (multi-file `event_ordering.rs`, selection-aware edits), the
//! vector panels (visibility + thread-local param bus), painter-layers
//! (curve/gradient sub-editors). Don't bend the macro to fit them — the
//! explicit code is clearer there, and the gates guard it either way.
//!
//! ## Shape
//!
//! ```ignore
//! ph2d_editor_core::panel_seam! {
//!     state: crate::state::MyPanelState,
//!     sliders: [ (SLIDER_ID, CHIP_ID, scale, offset), ... ],   // bipolar slider + px chip
//!     forward_buttons: [ APPLY_ID, RESET_ID, ... ],            // Click → ToolPanelEvent(Click)
//!     cancel_buttons: [ CANCEL_ID ],                           // Click → CancelActiveTool
//! }
//! ```
//!
//! Generates `pub fn populate(&mut WidgetStore)` and
//! `pub(crate) fn apply_event(&mut State, &mut dyn PanelHostInternal,
//! WidgetEvent) -> EventOutcome` — the exact two fns the `Panel` impl forwards
//! to. Any group may be an empty list. Sliders register as bipolar (track
//! `0.5` neutral) with `link_slider_number_mapped`; the chip's `ValueChanged`
//! is swallowed (the dispatch mirror keeps chip↔slider in lockstep, so the
//! tool is notified once, keyed off the slider — same contract as the
//! hand-written panels).

use crate::interaction::InteractiveState;
use crate::panel::PanelHostInternal;
use crate::widget::ButtonState;
use ph2d_a11y::NodeId;

/// Reset a button's pressed look to `Normal` after it fires. Shared by the
/// `panel_seam!`-generated `apply_event` so the macro body stays small. No-op
/// if `id` isn't a registered button.
pub fn seam_reset_button(host: &mut dyn PanelHostInternal, id: NodeId) {
    if let Some(InteractiveState::Button { state }) = host.store_mut().get_mut(id) {
        *state = ButtonState::Normal;
    }
}

#[macro_export]
macro_rules! panel_seam {
    (
        state: $State:ty,
        sliders: [ $( ( $slider:path, $chip:path, $scale:expr, $offset:expr ) ),* $(,)? ],
        forward_buttons: [ $( $fbtn:path ),* $(,)? ],
        cancel_buttons: [ $( $cbtn:path ),* $(,)? ] $(,)?
    ) => {
        /// Pre-register this panel's widgets in the `WidgetStore` at host boot.
        /// Generated by `ph2d_editor_core::panel_seam!`.
        pub fn populate(store: &mut $crate::interaction::WidgetStore) {
            $(
                store.register(
                    $fbtn,
                    $crate::interaction::InteractiveState::Button {
                        state: $crate::widget::ButtonState::Normal,
                    },
                );
            )*
            $(
                store.register(
                    $cbtn,
                    $crate::interaction::InteractiveState::Button {
                        state: $crate::widget::ButtonState::Normal,
                    },
                );
            )*
            $(
                store.register(
                    $slider,
                    $crate::interaction::InteractiveState::Slider {
                        state: $crate::widget::SliderState::Normal,
                        value: 0.5,
                        orientation: $crate::widget::SliderOrientation::Horizontal,
                    },
                );
                store.register(
                    $chip,
                    $crate::interaction::InteractiveState::NumberInput {
                        state: $crate::widget::TextInputState::Normal,
                        value: 0.0,
                        buffer: ::std::string::String::from("0"),
                        caret: 0,
                        last_committed: 0.0,
                        selection_anchor: ::core::option::Option::None,
                    },
                );
                store.link_slider_number_mapped($slider, $chip, $scale, $offset);
            )*
        }

        /// Classify one `WidgetEvent` into a tool-agnostic `PanelEvent` and push
        /// it on the action bus. Generated by `ph2d_editor_core::panel_seam!`.
        pub(crate) fn apply_event(
            _state: &mut $State,
            host: &mut dyn $crate::panel::PanelHostInternal,
            ev: $crate::interaction::WidgetEvent,
        ) -> $crate::panel::EventOutcome {
            let consumed = match ev {
                $(
                    // Slider drag (or mirror from the chip): forward the live
                    // track; the tool projects it to its natural unit.
                    $crate::interaction::WidgetEvent::ValueChanged(id) if id == $slider => {
                        let track = host.store().slider(id).map(|(_, v)| v).unwrap_or(0.5);
                        host.bus_mut().push($crate::action_bus::EditorAction::ToolPanelEvent(
                            $crate::tool::PanelEvent::SetValue(id, track as f64),
                        ));
                        true
                    }
                    // Chip edit already mirrored to the slider (which fires its
                    // own ValueChanged, handled above): swallow to avoid a
                    // double notify for the same edit.
                    $crate::interaction::WidgetEvent::ValueChanged(id) if id == $chip => true,
                )*
                $(
                    $crate::interaction::WidgetEvent::Click(id) if id == $fbtn => {
                        $crate::panel::seam_reset_button(host, id);
                        host.bus_mut().push($crate::action_bus::EditorAction::ToolPanelEvent(
                            $crate::tool::PanelEvent::Click(id),
                        ));
                        true
                    }
                )*
                $(
                    $crate::interaction::WidgetEvent::Click(id) if id == $cbtn => {
                        $crate::panel::seam_reset_button(host, id);
                        host.bus_mut().push($crate::action_bus::EditorAction::CancelActiveTool);
                        true
                    }
                )*
                _ => false,
            };
            $crate::panel::EventOutcome::from_bool(consumed)
        }
    };
}
