//! **GATE DE STALENESS do painel gerado** — o que o cabeçalho dele sempre prometeu.
//!
//! O `src/generated/panel.rs` abre com *"@generated by ph2d-ui-codegen — NÃO EDITE À MÃO. Editar a
//! SAÍDA de um gerador é o que deixa o gate de staleness vermelho"*.
//!
//! ⚠️ **Medido em 2026-08-09: esse gate não existia.** Nada no repo chamava `emit()` fora dos
//! testes de unidade da própria crate do gerador, e o diretório `golden/` dela está **vazio e nem
//! sequer versionado**. O arquivo podia ser editado à mão, ou o emissor mudar de formato, e nada
//! ficava vermelho — sob um cabeçalho que afirmava o contrário. *Um aviso que nomeia uma defesa
//! inexistente é pior que aviso nenhum: ele faz quem edita achar que será apanhado.*
//!
//! # O que ele consegue provar, e o que NÃO consegue
//!
//! Ele reconstrói a `PanelSpec` a partir das **constantes Rust** que o próprio arquivo declara
//! (`PANEL_ID`, `PANEL_TITLE`, `ROWS`) — sem parser de texto — e exige que `emit()` reproduza o
//! arquivo **byte a byte**.
//!
//! ⚠️ **Isto apanha** toda edição à mão do TEXTO que o emissor não saberia produzir (formatação,
//! um doc-comment reescrito, o cabeçalho mexido, uma row acrescentada fora da tabela) **e** o
//! emissor mudar de formato sem alguém regerar o arquivo — que são as duas metades da cicatriz que
//! o cabeçalho nomeia.
//!
//! ⚠️ **Isto NÃO apanha** o arquivo descrever uma cena diferente da que o artista tem: os DADOS
//! são a entrada, e nenhum gate pode compará-los com um documento que não está versionado. Para
//! isso seria preciso congelar uma cena de fixture no repo — decisão de produto, não uma correção
//! mecânica, e fica nomeada aqui em vez de escondida atrás de um nome de teste ambicioso.

use ph2d_panel_authored::generated::{PANEL_ID, PANEL_TITLE, ROWS};
use ph2d_ui_codegen::{PanelSpec, RowSpec, emit};

/// O caminho do arquivo gerado, relativo à raiz desta crate.
const GENERATED: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated/panel.rs");

/// A `PanelSpec` que o arquivo DECLARA, reconstruída das constantes que ele exporta.
///
/// ⚠️ **Sem parser de texto, e a diferença é o que torna o gate honesto:** ler os dados de volta do
/// próprio texto que se vai comparar seria circular. Aqui o compilador já leu — `ROWS` é uma
/// `&[RowConst]` — e a única coisa reconstruída é a FORMA que o emissor produz a partir dela.
fn spec_the_file_declares() -> PanelSpec {
    PanelSpec {
        id: PANEL_ID.to_string(),
        title: PANEL_TITLE.to_string(),
        rows: ROWS
            .iter()
            .map(|r| RowSpec {
                kind: r.kind.ident().to_string(),
                label: r.label.to_string(),
                key: r.key.to_string(),
                rgba: r.rgba,
                icon: r.icon.map(str::to_string),
                icon_slug: r.icon_slug.map(str::to_string),
                options: r.options.iter().map(|o| (*o).to_string()).collect(),
            })
            .collect(),
    }
}

/// **CONTROLE POSITIVO.** O arquivo é o que este gate pensa que é.
///
/// ⚠️ Sem isto, mover o gerado (ou renomear a pasta) faz o `read_to_string` explodir com uma
/// mensagem de IO em vez de dizer que o gate perdeu o sujeito — e uma tabela vazia lida de um
/// arquivo que não existe compararia nada com nada.
#[test]
fn the_generated_file_is_where_this_gate_thinks_it_is() {
    let src = std::fs::read_to_string(GENERATED).expect("o painel gerado e legivel");
    assert!(
        src.starts_with("// @generated by ph2d-ui-codegen"),
        "o arquivo em {GENERATED} nao e' o painel gerado"
    );
    assert!(
        !ROWS.is_empty(),
        "a tabela gerada esta' VAZIA — a comparacao passaria por vacuo"
    );
}

/// **O arquivo versionado é, ao byte, o que o emissor emite para os dados que ele declara.**
#[test]
fn the_generated_panel_is_what_the_emitter_emits() {
    let on_disk = std::fs::read_to_string(GENERATED).expect("o painel gerado e legivel");
    let emitted = emit(&spec_the_file_declares());
    assert_eq!(
        on_disk, emitted,
        "o `src/generated/panel.rs` versionado difere do que o `ph2d-ui-codegen::emit` produz \
         para os dados que o proprio arquivo declara.\n\
         Ou alguem o editou a' MAO (o cabecalho dele diz para nao o fazer), ou o emissor mudou de \
         formato e ninguem regerou o arquivo."
    );
}

/// **REGERA o arquivo** a partir dos dados que ele declara — a resposta ao gate acima quando quem
/// mudou foi o EMISSOR.
///
/// ```text
/// cargo test -p ph2d-panel-authored --test the_generated_panel_is_what_the_emitter_emits \
///     regenerate -- --ignored
/// ```
///
/// ⚠️ **`#[ignore]` porque ele ESCREVE**, e um teste que escreve no repo não pode correr na
/// varredura. E ele existe porque a alternativa é o que o cabeçalho do arquivo proíbe: sem esta
/// porta, a maneira óbvia de apagar o vermelho do gate é editar o gerado à mão — *a correção que
/// reintroduz o defeito*.
///
/// ⚠️ **Ele NÃO re-lê a cena do artista**, então só serve para mudanças de FORMATO. Se o que mudou
/// foi o desenho, quem regera é o app.
#[test]
#[ignore = "escreve no repo; rode a mao apos mudar o emissor"]
fn regenerate_the_panel_from_the_data_it_declares() {
    let emitted = emit(&spec_the_file_declares());
    std::fs::write(GENERATED, &emitted).expect("o painel gerado e' gravavel");
    println!("regerado: {GENERATED} ({} bytes)", emitted.len());
}
