//! Widget `NodeId`s for the Color Equalization panel — re-exports from
//! the tool crate's `ids` module (single source of truth in
//! `ph2d-tool-color-equalization/src/ids.rs`, derived via `hash_node_id`).
//!
//! Mirrors the `ph2d-panel-padding` convenience module — every panel
//! internal writes `crate::ids::CEQ_*`, and the tool's
//! `handle_panel_event` matches against the same hashes.

pub use ph2d_tool_color_equalization::ids::{
    CEQ_APPLY, CEQ_AUTO_COLORS, CEQ_AUTO_CONTRAST, CEQ_AUTO_LEVELS, CEQ_AUTO_WB, CEQ_BRIGHTNESS,
    CEQ_BRIGHTNESS_NUM, CEQ_CANCEL, CEQ_CLIP_LIMIT, CEQ_CLIP_LIMIT_NUM, CEQ_CONTRAST,
    CEQ_CONTRAST_NUM, CEQ_EXPOSURE, CEQ_EXPOSURE_NUM, CEQ_LUT_1_DROPDOWN, CEQ_LUT_1_OPTS,
    CEQ_LUT_2_DROPDOWN, CEQ_LUT_2_OPTS, CEQ_LUT_INTENSITY, CEQ_LUT_INTENSITY_NUM, CEQ_LUT_MIX,
    CEQ_LUT_MIX_NUM, CEQ_PANEL, CEQ_POSTERIZE_DITHER_GRAIN, CEQ_POSTERIZE_DITHER_GRAIN_NUM,
    CEQ_POSTERIZE_DITHER_STRENGTH, CEQ_POSTERIZE_DITHER_STRENGTH_NUM, CEQ_POSTERIZE_DITHERING,
    CEQ_POSTERIZE_DROPDOWN, CEQ_POSTERIZE_LEVELS, CEQ_POSTERIZE_OPTS, CEQ_QUANTIZE_COLORS,
    CEQ_QUANTIZE_DROPDOWN, CEQ_QUANTIZE_OPTS, CEQ_RESET, CEQ_SATURATION, CEQ_SATURATION_NUM,
    CEQ_SHARPEN_AMOUNT, CEQ_SHARPEN_AMOUNT_NUM, CEQ_SHARPEN_RADIUS, CEQ_SHARPEN_RADIUS_NUM,
    CEQ_TEMPERATURE, CEQ_TEMPERATURE_NUM, CEQ_TILE_GRID, CEQ_TILE_GRID_NUM, CEQ_TINT, CEQ_TINT_NUM,
    CEQ_VIBRANCE, CEQ_VIBRANCE_NUM,
};
