//! Single source of truth for the MCP tool catalog (HR-10 parity).
//!
//! Both the runtime [`crate::Server::register_default_tools`] and the
//! `ph2d-bindgen` codegen tool consume [`CATALOG`]. Changing the
//! catalog here propagates to:
//!   - The MCP server's registered tools.
//!   - `runtime/mcp/schema.json` (regenerated by ph2d-bindgen, parity
//!     enforced in CI — drift fails the build).
//!   - `runtime/luau/ph2d.d.luau` (Luau type definitions, same
//!     pipeline).
//!
//! Schema fragments are stored as `&'static str` JSON literals so the
//! whole catalog stays `const`. The runtime and codegen both
//! `serde_json::from_str` on demand.

/// Static description of one tool exposed over MCP.
pub struct ToolSpec {
    pub name: &'static str,
    pub description: &'static str,
    /// Per HR-11: destructive tools require a `confirmation_token` in
    /// the request payload (single-use, 5 min TTL) unless the server
    /// is launched with `--unsafe-mcp`.
    pub destructive: bool,
    /// JSON Schema fragment (object) describing accepted params.
    pub input_schema_json: &'static str,
    /// JSON Schema fragment describing the return value.
    pub output_schema_json: &'static str,
    /// Luau function signature emitted into `runtime/luau/ph2d.d.luau`.
    /// Format: `fn_name(arg1: type, arg2: type): return_type` —
    /// human-friendly subset, not full Luau type syntax.
    pub luau_signature: &'static str,
}

/// The 5 canonical tools (from `docs/scripting/mcp/c6-prompts.md`).
/// Order is stable — bindgen output is sorted by name independently
/// so reordering here doesn't churn artifacts, but additions /
/// removals do.
pub const CATALOG: &[ToolSpec] = &[
    ToolSpec {
        name: "scene.spawn_entity",
        description: "Spawn empty entity in current scene; returns Entity handle.",
        destructive: false,
        input_schema_json: r#"{"type":"object","properties":{}}"#,
        output_schema_json: r#"{"type":"object","properties":{"entity":{"type":"integer"}},"required":["entity"]}"#,
        luau_signature: "spawn_entity(): { entity: number }",
    },
    ToolSpec {
        name: "scene.add_component",
        description: "Attach a component to an entity. Component data is JSON-serialized.",
        destructive: false,
        input_schema_json: r#"{"type":"object","properties":{"entity":{"type":"integer"},"component":{"type":"string"},"data":{"type":"object"}},"required":["entity","component","data"]}"#,
        output_schema_json: r#"{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"]}"#,
        luau_signature: "add_component(entity: number, component: string, data: any): { ok: boolean }",
    },
    ToolSpec {
        name: "scene.get_component",
        description: "Read a component by name from an entity. Returns null when absent.",
        destructive: false,
        input_schema_json: r#"{"type":"object","properties":{"entity":{"type":"integer"},"component":{"type":"string"}},"required":["entity","component"]}"#,
        output_schema_json: r#"{"type":"object","properties":{"data":{}}}"#,
        luau_signature: "get_component(entity: number, component: string): { data: any }",
    },
    ToolSpec {
        name: "message.send",
        description: "Send a Defold-style message to a target entity.",
        destructive: false,
        input_schema_json: r#"{"type":"object","properties":{"target":{"type":"integer"},"message":{"type":"string"},"payload":{"type":"object"}},"required":["target","message"]}"#,
        output_schema_json: r#"{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"]}"#,
        luau_signature: "send(target: number, message: string, payload: any): { ok: boolean }",
    },
    ToolSpec {
        name: "scene.delete_entity",
        description: "Despawn an entity. Destructive — requires confirmation_token (HR-11).",
        destructive: true,
        input_schema_json: r#"{"type":"object","properties":{"entity":{"type":"integer"},"confirmation_token":{"type":"string"}},"required":["entity","confirmation_token"]}"#,
        output_schema_json: r#"{"type":"object","properties":{"removed":{"type":"boolean"}},"required":["removed"]}"#,
        luau_signature: "delete_entity(entity: number, confirmation_token: string): { removed: boolean }",
    },
    // ─── ADR-0025 M14.2: LuauScript Component + lateral state ────────
    // These are top-level (no dot in name) so the generated `Ph2d`
    // type exposes them flat as `ph2d.attach_script(...)` matching the
    // runtime API in `crates/ph2d-script/src/host.rs::wire_ph2d_api`.
    ToolSpec {
        name: "attach_script",
        description: "Attach a LuauScript component to an entity. bytecode is the 64-char hex AssetId of compiled Luau.",
        destructive: false,
        input_schema_json: r#"{"type":"object","properties":{"entity":{"type":"integer"},"bytecode":{"type":"string","pattern":"^[0-9a-f]{64}$"}},"required":["entity","bytecode"]}"#,
        output_schema_json: r#"{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"]}"#,
        luau_signature: "attach_script(entity: number, bytecode: string): { ok: boolean }",
    },
    ToolSpec {
        name: "find_by_name",
        description: "Resolve a Name component to its Entity id. Returns null when absent.",
        destructive: false,
        input_schema_json: r#"{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}"#,
        output_schema_json: r#"{"type":"object","properties":{"entity":{"type":["integer","null"]}}}"#,
        luau_signature: "find_by_name(name: string): number?",
    },
    ToolSpec {
        name: "state_get",
        description: "Read a per-entity lateral state field (HR-16 POD value). Returns null when absent.",
        destructive: false,
        input_schema_json: r#"{"type":"object","properties":{"entity":{"type":"integer"},"field":{"type":"string"}},"required":["entity","field"]}"#,
        output_schema_json: r#"{"type":"object","properties":{"value":{}}}"#,
        luau_signature: "state_get(entity: number, field: string): any",
    },
    ToolSpec {
        name: "state_set",
        description: "Write a per-entity lateral state field. Value must be POD (HR-16): number/string/bool/nil or nested table thereof.",
        destructive: false,
        input_schema_json: r#"{"type":"object","properties":{"entity":{"type":"integer"},"field":{"type":"string"},"value":{}},"required":["entity","field","value"]}"#,
        output_schema_json: r#"{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"]}"#,
        luau_signature: "state_set(entity: number, field: string, value: any): ()",
    },
    ToolSpec {
        name: "state_keys",
        description: "Alphabetically-sorted list of lateral state field names for an entity.",
        destructive: false,
        input_schema_json: r#"{"type":"object","properties":{"entity":{"type":"integer"}},"required":["entity"]}"#,
        output_schema_json: r#"{"type":"object","properties":{"keys":{"type":"array","items":{"type":"string"}}},"required":["keys"]}"#,
        luau_signature: "state_keys(entity: number): { string }",
    },
    // ─── ADR-0061 P4: LLM4SVG vector authoring (Inovação #4) ─────────
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_has_expected_tool_count() {
        // 5 base (M9, c6-prompts.md gate) + 5 M14.2 additions
        // (script.attach + scene.find_by_name + state.get/set/keys).
        // (6 ADR-0061 P4 vector.* tools retired with the vector module, ADR-0108.)
        // Adjust this number deliberately when adding tools so PRs
        // surface API surface changes for review (HR-10 parity).
        assert_eq!(CATALOG.len(), 10);
    }

    #[test]
    fn names_are_unique() {
        let mut names: Vec<&str> = CATALOG.iter().map(|t| t.name).collect();
        let n = names.len();
        names.sort();
        names.dedup();
        assert_eq!(names.len(), n, "duplicate tool name in CATALOG");
    }

    #[test]
    fn schema_fragments_parse_as_valid_json() {
        for t in CATALOG {
            serde_json::from_str::<serde_json::Value>(t.input_schema_json)
                .unwrap_or_else(|e| panic!("input_schema for {} is invalid JSON: {e}", t.name));
            serde_json::from_str::<serde_json::Value>(t.output_schema_json)
                .unwrap_or_else(|e| panic!("output_schema for {} is invalid JSON: {e}", t.name));
        }
    }

    #[test]
    fn destructive_tools_require_confirmation_token() {
        for t in CATALOG.iter().filter(|t| t.destructive) {
            assert!(
                t.input_schema_json.contains("confirmation_token"),
                "destructive tool {} must declare confirmation_token in input schema (HR-11)",
                t.name
            );
        }
    }
}
