//! O **overlay do Blend Object** (ADR-0122) — módulo irmão (LOC cap).
//!
//! O Blend do Illustrator é um objeto único cujos passos intermediários são **virtuais**: *"they
//! do not have anchor points, control handles, fills or strokes, but are merely an appearance
//! generated by the blend object."* Só as fontes e o spine carregam geometria de verdade.
//!
//! É isto: a shell coze o **overlay ordenado** por frame (em MUNDO, cor interpolada em OKLab) e o
//! passa aqui. O overlay são os passos de cada elo INTERCALADOS com a fonte de cima dele — a pilha
//! de z do Illustrator (fonte0 embaixo → passos → fonte1 → …). Os passos **não estão na cena** —
//! não são pickáveis, não poluem a hierarquia, e somem no frame em que o blend deixa de existir.
//! É o que torna o blend **um objeto**, e não N formas.
//!
//! # Desenha pela MESMA porta que a arte real
//!
//! Cada item do overlay é arte de verdade (fill + stroke que **escalam com o mundo**, ao contrário
//! do véu do Build — ver [`crate::draw_build_faces`]). Desenhá-lo por um caminho próprio faria a
//! transição divergir do que a mesma forma pareceria como path real. Por isso cada item passa por
//! [`crate::draw_path`], exatamente como um item de [`crate::dispatch`].

use ph2d_vec_scene::VecPath;
use ph2d_vector::{Affine, VectorScene};

/// Desenha o `overlay` (já em MUNDO — a shell o cozeu a partir das fontes cozidas) sob `camera` (o
/// afim mundo→tela), **na ordem** (é a ordem de z). Cada item carrega a própria cor.
///
/// Vazio ⇒ nada é emitido: sem blend na cena, o passe é um no-op.
pub fn draw_blend_overlay(overlay: &[VecPath], camera: Affine, target: &mut VectorScene) {
    for item in overlay {
        crate::draw_path(item, camera, target);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ph2d_vec_scene::{Paint, Rgba8, VecVertex};

    fn square(fill: [u8; 3]) -> VecPath {
        VecPath {
            verts: [[0.0, 0.0], [2.0, 0.0], [2.0, 2.0], [0.0, 2.0]]
                .map(VecVertex::corner)
                .to_vec(),
            closed: true,
            fill: Some(Paint::solid(Rgba8::new(fill[0], fill[1], fill[2], 255))),
            ..VecPath::default()
        }
    }

    /// Cada item VIRA um desenho, na ordem dada — é o passe inteiro: N formas coloridas na tela,
    /// empilhadas, sem N entidades na cena.
    #[test]
    fn each_item_becomes_one_drawn_path_in_order() {
        let overlay = vec![
            square([200, 0, 0]),
            square([0, 200, 0]),
            square([0, 0, 200]),
        ];
        let mut scene = VectorScene::new();
        draw_blend_overlay(&overlay, Affine::IDENTITY, &mut scene);
        assert_eq!(scene.inner().encoding().n_paths, 3, "um path por item");
    }

    /// Sem overlay, nada é emitido — o passe não desenha no vazio (o frame em que o blend some não
    /// deixa fantasmas na tela).
    #[test]
    fn nothing_is_drawn_without_overlay() {
        let mut scene = VectorScene::new();
        draw_blend_overlay(&[], Affine::IDENTITY, &mut scene);
        assert_eq!(scene.inner().encoding().n_paths, 0);
    }
}
