//! Os **passos virtuais** do Blend Object (ADR-0122) — módulo irmão (LOC cap).
//!
//! O Blend do Illustrator é um objeto único cujos passos intermediários são **virtuais**: *"they
//! do not have anchor points, control handles, fills or strokes, but are merely an appearance
//! generated by the blend object."* Só as fontes e o spine carregam geometria de verdade.
//!
//! É isto: a shell coze os N passos por frame (em MUNDO, com a cor interpolada em OKLab) e os
//! passa aqui. Eles **não estão na cena** — não são pickáveis, não poluem a hierarquia, e
//! desaparecem no frame em que o blend deixa de existir. É o que torna o blend **um objeto**, e
//! não N formas.
//!
//! # Desenham pela MESMA porta que a arte real
//!
//! Um passo é arte de verdade (fill + stroke que **escalam com o mundo**, ao contrário do véu do
//! Build — ver [`crate::draw_build_faces`]). Desenhá-lo por um caminho próprio faria a transição
//! divergir do que a mesma forma pareceria como path real. Por isso cada passo passa por
//! [`crate::draw_path`], exatamente como um item de [`crate::dispatch`].

use ph2d_vec_scene::VecPath;
use ph2d_vector::{Affine, VectorScene};

/// Desenha os passos `steps` (já em MUNDO — a shell os cozeu a partir das fontes cozidas) sob
/// `camera` (o afim mundo→tela). Cada passo carrega a própria cor interpolada.
///
/// Vazio ⇒ nada é emitido: sem blend na cena, o passe é um no-op.
pub fn draw_blend_steps(steps: &[VecPath], camera: Affine, target: &mut VectorScene) {
    for step in steps {
        crate::draw_path(step, camera, target);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ph2d_vec_scene::{Paint, Rgba8, VecVertex};

    fn square(fill: [u8; 3]) -> VecPath {
        VecPath {
            verts: [[0.0, 0.0], [2.0, 0.0], [2.0, 2.0], [0.0, 2.0]]
                .map(VecVertex::corner)
                .to_vec(),
            closed: true,
            fill: Some(Paint::solid(Rgba8::new(fill[0], fill[1], fill[2], 255))),
            ..VecPath::default()
        }
    }

    /// Cada passo VIRA um desenho — é o passe inteiro: N formas coloridas na tela sem N entidades
    /// na cena.
    #[test]
    fn each_step_becomes_one_drawn_path() {
        let steps = vec![
            square([200, 0, 0]),
            square([0, 200, 0]),
            square([0, 0, 200]),
        ];
        let mut scene = VectorScene::new();
        draw_blend_steps(&steps, Affine::IDENTITY, &mut scene);
        assert_eq!(scene.inner().encoding().n_paths, 3, "um path por passo");
    }

    /// Sem passos, nada é emitido — o passe não desenha no vazio (o frame em que o blend some não
    /// deixa fantasmas na tela).
    #[test]
    fn nothing_is_drawn_without_steps() {
        let mut scene = VectorScene::new();
        draw_blend_steps(&[], Affine::IDENTITY, &mut scene);
        assert_eq!(scene.inner().encoding().n_paths, 0);
    }
}
