//! Widget `NodeId`s for the Vector Style panel.
//!
//! Like the other panel crates, the ids stay defined in editor-core
//! (`ph2d_editor_core::ids`) — the layout + z-order walk + `node_id_collisions`
//! arch test all reference them, and re-defining them here would fork the
//! source of truth. This module is a convenience re-export so the panel's
//! internal modules (and the tool, via `handle_panel_event`) can write
//! `crate::ids::VECTOR_*`.

/// O 6º pill de modo: **Connect** — a linha que gruda em duas formas e as segue.
pub use ph2d_editor_core::ids::VECTOR_MODE_CONNECT;
/// Pontas de traço (arrowheads): os dois chips + as opções do popover, por `slot`
/// (0 = começo, 1 = fim) e índice em `ph2d_vec_scene::ALL_MARKERS`.
pub use ph2d_editor_core::ids::{
    MARKER_SLOTS, MAX_MARKER_OPTIONS, VECTOR_MARKER_END_DD, VECTOR_MARKER_START_DD,
    vector_marker_option_id,
};
pub use ph2d_editor_core::ids::{
    MAX_SHAPE_FIELD_SLOTS, vector_shape_choice_id, vector_shape_field_id, vector_shape_group_id,
    vector_shape_id,
};
pub use ph2d_editor_core::ids::{
    MAX_TEXT_VARIATION_AXES, vector_text_axis_id, vector_text_font_option_id,
};
pub use ph2d_editor_core::ids::{
    VECTOR_ALIGN_BOTTOM, VECTOR_ALIGN_HCENTER, VECTOR_ALIGN_LEFT, VECTOR_ALIGN_RIGHT,
    VECTOR_ALIGN_TOP, VECTOR_ALIGN_VCENTER, VECTOR_ARRANGE_BACKWARD, VECTOR_ARRANGE_DUPLICATE,
    VECTOR_ARRANGE_FLIP_H, VECTOR_ARRANGE_FLIP_V, VECTOR_ARRANGE_FORWARD,
    VECTOR_ARRANGE_ROTATE_CCW, VECTOR_ARRANGE_ROTATE_CW, VECTOR_ARRANGE_TO_BACK,
    VECTOR_ARRANGE_TO_FRONT, VECTOR_BOOL_EXCLUDE, VECTOR_BOOL_INTERSECT, VECTOR_BOOL_SUBTRACT,
    VECTOR_BOOL_UNION, VECTOR_CAP_BUTT, VECTOR_CAP_ROUND, VECTOR_CAP_SQUARE, VECTOR_CLOSE,
    VECTOR_COMPOUND_MAKE, VECTOR_COMPOUND_RELEASE, VECTOR_CONVERT_TO_CURVES, VECTOR_DASH,
    VECTOR_DASH_NUM, VECTOR_DISTRIBUTE_H, VECTOR_DISTRIBUTE_V, VECTOR_FILL_KIND_LINEAR,
    VECTOR_FILL_KIND_MULTI, VECTOR_FILL_KIND_RADIAL, VECTOR_FILL_KIND_SOLID, VECTOR_FILL_OPACITY,
    VECTOR_FILL_OPACITY_NUM, VECTOR_FILL_RULE_EVENODD, VECTOR_FILL_RULE_NONZERO,
    VECTOR_FILL_SWATCH, VECTOR_GAP, VECTOR_GAP_NUM, VECTOR_GRAD_ADD_POINT, VECTOR_GRAD_ADD_STOP,
    VECTOR_GRAD_ANGLE, VECTOR_GRAD_ANGLE_NUM, VECTOR_GRAD_INFLUENCE, VECTOR_GRAD_INFLUENCE_NUM,
    VECTOR_GRAD_JITTER, VECTOR_GRAD_JITTER_NUM, VECTOR_GRAD_REMOVE_POINT, VECTOR_GRAD_REMOVE_STOP,
    VECTOR_JOIN_BEVEL, VECTOR_JOIN_MITER, VECTOR_JOIN_ROUND, VECTOR_MODE_NODE, VECTOR_MODE_PEN,
    VECTOR_MODE_SELECT, VECTOR_MODE_TEXT, VECTOR_PANEL, VECTOR_PATH_CLOSE, VECTOR_PATH_SHARPEN,
    VECTOR_PATH_SIMPLIFY, VECTOR_PATH_SMOOTH, VECTOR_PATH_SUBDIVIDE, VECTOR_PIVOT_EDIT,
    VECTOR_SNAP_OFF, VECTOR_SNAP_ON, VECTOR_STROKE_OPACITY, VECTOR_STROKE_OPACITY_NUM,
    VECTOR_STROKE_SWATCH, VECTOR_TEXT_ALIGN_CENTER, VECTOR_TEXT_ALIGN_LEFT,
    VECTOR_TEXT_ALIGN_RIGHT, VECTOR_TEXT_FONT_DD, VECTOR_TEXT_FONT_IMPORT, VECTOR_TEXT_FONT_NEXT,
    VECTOR_TEXT_FONT_PREV, VECTOR_TEXT_LINE_HEIGHT, VECTOR_TEXT_LINE_HEIGHT_NUM, VECTOR_TEXT_SIZE,
    VECTOR_TEXT_SIZE_NUM, VECTOR_TEXT_TRACKING, VECTOR_TEXT_TRACKING_NUM, VECTOR_TEXT_WEIGHT,
    VECTOR_TEXT_WEIGHT_NUM, VECTOR_TRANSFORM_H, VECTOR_TRANSFORM_R, VECTOR_TRANSFORM_W,
    VECTOR_TRANSFORM_X, VECTOR_TRANSFORM_Y, VECTOR_VERT_CORNER, VECTOR_VERT_DELETE,
    VECTOR_VERT_SMOOTH, VECTOR_VERT_SYMMETRIC, VECTOR_WIDTH, VECTOR_WIDTH_NUM,
};
/// Os cabeçalhos COLAPSÁVEIS (canon `section_header.md`) + o 5º pill de modo + o chip de
/// categoria do catálogo. `VECTOR_SECTIONS` é a lista que o `populate` marca como
/// colapsável — uma seção fora dela pinta um chevron que não dobra.
pub use ph2d_editor_core::ids::{
    VECTOR_MODE_SHAPE, VECTOR_SECTION_ALIGN, VECTOR_SECTION_ARRANGE, VECTOR_SECTION_AXES,
    VECTOR_SECTION_BOOLEAN, VECTOR_SECTION_FILL, VECTOR_SECTION_FILL_TYPE, VECTOR_SECTION_FONT,
    VECTOR_SECTION_PARAGRAPH, VECTOR_SECTION_PATH, VECTOR_SECTION_SHAPE,
    VECTOR_SECTION_SHAPE_PARAMS, VECTOR_SECTION_SNAP, VECTOR_SECTION_STROKE, VECTOR_SECTION_TEXT,
    VECTOR_SECTION_TOOL, VECTOR_SECTION_TRANSFORM, VECTOR_SECTION_VERTEX, VECTOR_SECTIONS,
    VECTOR_SHAPE_GROUP_DD,
};
