//! Widget `NodeId`s for the Vector Style panel.
//!
//! Like the other panel crates, the ids stay defined in editor-core
//! (`ph2d_editor_core::ids`) — the layout + z-order walk + `node_id_collisions`
//! arch test all reference them, and re-defining them here would fork the
//! source of truth. This module is a convenience re-export so the panel's
//! internal modules (and the tool, via `handle_panel_event`) can write
//! `crate::ids::VECTOR_*`.

pub use ph2d_editor_core::ids::{
    VECTOR_ARRANGE_BACKWARD, VECTOR_ARRANGE_DUPLICATE, VECTOR_ARRANGE_FLIP_H,
    VECTOR_ARRANGE_FLIP_V, VECTOR_ARRANGE_FORWARD, VECTOR_ARRANGE_ROTATE_CCW,
    VECTOR_ARRANGE_ROTATE_CW, VECTOR_ARRANGE_TO_BACK, VECTOR_ARRANGE_TO_FRONT, VECTOR_BOOL_EXCLUDE,
    VECTOR_BOOL_INTERSECT, VECTOR_BOOL_SUBTRACT, VECTOR_BOOL_UNION, VECTOR_CAP_BUTT,
    VECTOR_CAP_ROUND, VECTOR_CAP_SQUARE, VECTOR_CLOSE, VECTOR_DASH, VECTOR_DASH_NUM,
    VECTOR_FILL_OPACITY, VECTOR_FILL_OPACITY_NUM, VECTOR_FILL_SWATCH, VECTOR_GAP, VECTOR_GAP_NUM,
    VECTOR_JOIN_BEVEL, VECTOR_JOIN_MITER, VECTOR_JOIN_ROUND, VECTOR_MODE_ELLIPSE, VECTOR_MODE_PEN,
    VECTOR_MODE_POLYGON, VECTOR_MODE_RECT, VECTOR_MODE_RRECT, VECTOR_MODE_SPIRAL, VECTOR_MODE_STAR,
    VECTOR_PANEL, VECTOR_PATH_SHARPEN, VECTOR_PATH_SMOOTH, VECTOR_RRECT_RADIUS,
    VECTOR_RRECT_RADIUS_NUM, VECTOR_SIDES, VECTOR_SIDES_NUM, VECTOR_SPIRAL_TURNS,
    VECTOR_SPIRAL_TURNS_NUM, VECTOR_STAR_INNER, VECTOR_STAR_INNER_NUM, VECTOR_STAR_POINTS,
    VECTOR_STAR_POINTS_NUM, VECTOR_STROKE_OPACITY, VECTOR_STROKE_OPACITY_NUM, VECTOR_STROKE_SWATCH,
    VECTOR_TRANSFORM_H, VECTOR_TRANSFORM_W, VECTOR_TRANSFORM_X, VECTOR_TRANSFORM_Y,
    VECTOR_VERT_CORNER, VECTOR_VERT_DELETE, VECTOR_VERT_SMOOTH, VECTOR_VERT_SYMMETRIC,
    VECTOR_WIDTH, VECTOR_WIDTH_NUM,
};
