//! Widget `NodeId`s for the Vector Style panel.
//!
//! Like the other panel crates, the ids stay defined in editor-core
//! (`ph2d_editor_core::ids`) — the layout + z-order walk + `node_id_collisions`
//! arch test all reference them, and re-defining them here would fork the
//! source of truth. This module is a convenience re-export so the panel's
//! internal modules (and the tool, via `handle_panel_event`) can write
//! `crate::ids::VECTOR_*`.

pub use ph2d_editor_core::ids::{
    VECTOR_ALIGN_BOTTOM, VECTOR_ALIGN_HCENTER, VECTOR_ALIGN_LEFT, VECTOR_ALIGN_RIGHT,
    VECTOR_ALIGN_TOP, VECTOR_ALIGN_VCENTER, VECTOR_ARC_DEGREES, VECTOR_ARC_DEGREES_NUM,
    VECTOR_ARRANGE_BACKWARD, VECTOR_ARRANGE_DUPLICATE, VECTOR_ARRANGE_FLIP_H,
    VECTOR_ARRANGE_FLIP_V, VECTOR_ARRANGE_FORWARD, VECTOR_ARRANGE_ROTATE_CCW,
    VECTOR_ARRANGE_ROTATE_CW, VECTOR_ARRANGE_TO_BACK, VECTOR_ARRANGE_TO_FRONT, VECTOR_BOOL_EXCLUDE,
    VECTOR_BOOL_INTERSECT, VECTOR_BOOL_SUBTRACT, VECTOR_BOOL_UNION, VECTOR_CAP_BUTT,
    VECTOR_CAP_ROUND, VECTOR_CAP_SQUARE, VECTOR_CLOSE, VECTOR_COMPOUND_MAKE,
    VECTOR_COMPOUND_RELEASE, VECTOR_DASH, VECTOR_DASH_NUM, VECTOR_DISTRIBUTE_H,
    VECTOR_DISTRIBUTE_V, VECTOR_FILL_KIND_LINEAR, VECTOR_FILL_KIND_MULTI, VECTOR_FILL_KIND_RADIAL,
    VECTOR_FILL_KIND_SOLID, VECTOR_FILL_OPACITY, VECTOR_FILL_OPACITY_NUM, VECTOR_FILL_RULE_EVENODD,
    VECTOR_FILL_RULE_NONZERO, VECTOR_FILL_SWATCH, VECTOR_GAP, VECTOR_GAP_NUM,
    VECTOR_GRAD_ADD_POINT, VECTOR_GRAD_ADD_STOP, VECTOR_GRAD_ANGLE, VECTOR_GRAD_ANGLE_NUM,
    VECTOR_GRAD_INFLUENCE, VECTOR_GRAD_INFLUENCE_NUM, VECTOR_GRAD_JITTER, VECTOR_GRAD_JITTER_NUM,
    VECTOR_GRAD_REMOVE_POINT, VECTOR_GRAD_REMOVE_STOP, VECTOR_JOIN_BEVEL, VECTOR_JOIN_MITER,
    VECTOR_JOIN_ROUND, VECTOR_MODE_ARC, VECTOR_MODE_ELLIPSE, VECTOR_MODE_LINE, VECTOR_MODE_NODE,
    VECTOR_MODE_PEN, VECTOR_MODE_POLYGON, VECTOR_MODE_RECT, VECTOR_MODE_RRECT, VECTOR_MODE_SELECT,
    VECTOR_MODE_SPIRAL, VECTOR_MODE_STAR, VECTOR_MODE_TEXT, VECTOR_PANEL, VECTOR_PATH_CLOSE,
    VECTOR_PATH_SHARPEN, VECTOR_PATH_SIMPLIFY, VECTOR_PATH_SMOOTH, VECTOR_PATH_SUBDIVIDE,
    VECTOR_PIVOT_EDIT, VECTOR_RRECT_RADIUS, VECTOR_RRECT_RADIUS_NUM, VECTOR_SIDES,
    VECTOR_SIDES_NUM, VECTOR_SNAP_OFF, VECTOR_SNAP_ON, VECTOR_SPIRAL_TURNS,
    VECTOR_SPIRAL_TURNS_NUM, VECTOR_STAR_INNER, VECTOR_STAR_INNER_NUM, VECTOR_STAR_POINTS,
    VECTOR_STAR_POINTS_NUM, VECTOR_STROKE_OPACITY, VECTOR_STROKE_OPACITY_NUM, VECTOR_STROKE_SWATCH,
    VECTOR_TEXT_FONT_IMPORT, VECTOR_TEXT_FONT_NEXT, VECTOR_TEXT_FONT_PREV, VECTOR_TEXT_SIZE,
    VECTOR_TEXT_SIZE_NUM, VECTOR_TEXT_WEIGHT, VECTOR_TEXT_WEIGHT_NUM, VECTOR_TRANSFORM_H,
    VECTOR_TRANSFORM_R, VECTOR_TRANSFORM_W, VECTOR_TRANSFORM_X, VECTOR_TRANSFORM_Y,
    VECTOR_VERT_CORNER, VECTOR_VERT_DELETE, VECTOR_VERT_SMOOTH, VECTOR_VERT_SYMMETRIC,
    VECTOR_WIDTH, VECTOR_WIDTH_NUM,
};
