#![forbid(unsafe_code)]
//! `ph2d-imageio-registry-init` — image I/O registration aggregation point.
//!
//! Two codegen'd entry points, both GENERATED by `cargo run -p
//! ph2d-imageio-sync` from a scan of `crates/ph2d-imageio-*` (ADR-0054
//! W0.T3); the staleness gate (`tests/staleness.rs`) fails CI if either
//! drifts. Adding a format = dropping a crate + running the sync — never
//! hand-editing these lists. Same "drop a crate, zero central edit"
//! mechanism the node + tool fan-outs use.
//!
//! - [`register_all_importers`] — every format with `pub fn
//!   register_importer`, for the [`ph2d_imageio::ImporterRegistry`].
//! - [`register_all_exporters`] — every format with `pub fn
//!   register_exporter`, for the [`ph2d_imageio::ExporterRegistry`].
//!
//! Both called once at boot from `shells/<plat>/src/init.rs` (W0.T6).

use ph2d_imageio::{ExporterRegistry, ImporterRegistry};

/// Register every importer with `reg`. The body is codegen'd between the
/// markers below.
///
/// `#[allow(unused_variables)]` covers the W0 window before W0.T5 lands
/// the first PNG stub — once the codegen populates the body with at
/// least one `<crate>::register_importer(reg);` line, `reg` is actually
/// used and the allow becomes a harmless no-op. Removed by W0.T5.
#[allow(unused_variables)]
pub fn register_all_importers(reg: &mut ImporterRegistry) {
    // <ph2d-imageio-sync:importers:begin>
    // <ph2d-imageio-sync:importers:end>
}

/// Register every exporter with `reg`. Body codegen'd.
///
/// Same `#[allow(unused_variables)]` rationale as
/// [`register_all_importers`]; removed by W0.T5 (PNG stub exposes
/// `register_exporter` too).
#[allow(unused_variables)]
pub fn register_all_exporters(reg: &mut ExporterRegistry) {
    // <ph2d-imageio-sync:exporters:begin>
    // <ph2d-imageio-sync:exporters:end>
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_all_importers_builds_empty_registry() {
        // W0 state: no format crates registered yet. Smoke that the
        // function compiles and the registry stays empty.
        let mut reg = ImporterRegistry::new();
        register_all_importers(&mut reg);
        assert!(reg.is_empty());
    }

    #[test]
    fn register_all_exporters_builds_empty_registry() {
        let mut reg = ExporterRegistry::new();
        register_all_exporters(&mut reg);
        assert!(reg.is_empty());
    }
}
