#![forbid(unsafe_code)]
//! `ph2d-imageio-registry-init` — image I/O registration aggregation point.
//!
//! Two codegen'd entry points, both GENERATED by `cargo run -p
//! ph2d-imageio-sync` from a scan of `crates/ph2d-imageio-*` (ADR-0054
//! W0.T3); the staleness gate (`tests/staleness.rs`) fails CI if either
//! drifts. Adding a format = dropping a crate + running the sync — never
//! hand-editing these lists. Same "drop a crate, zero central edit"
//! mechanism the node + tool fan-outs use.
//!
//! - [`register_all_importers`] — every format with `pub fn
//!   register_importer`, for the [`ph2d_imageio::ImporterRegistry`].
//! - [`register_all_exporters`] — every format with `pub fn
//!   register_exporter`, for the [`ph2d_imageio::ExporterRegistry`].
//!
//! Both called once at boot from `shells/<plat>/src/init.rs` (W0.T6).

use ph2d_imageio::{ExporterRegistry, ImporterRegistry};

/// Register every importer with `reg`. The body is codegen'd between
/// the markers below — adding a format = drop a `crates/ph2d-imageio-*`
/// crate exposing `pub fn register_importer` + run `cargo run -p
/// ph2d-imageio-sync`. Never hand-edit between the markers.
///
/// Order of calls does not affect correctness — [`ImporterRegistry::find_for`]
/// dispatches by [`ph2d_imageio::ImageImporter::supports`], not source
/// order. Alphabetical order in the codegen is merge-conflict hygiene.
pub fn register_all_importers(reg: &mut ImporterRegistry) {
    // <ph2d-imageio-sync:importers:begin>
    ph2d_imageio_gif::register_importer(reg);
    ph2d_imageio_jpeg::register_importer(reg);
    ph2d_imageio_png::register_importer(reg);
    ph2d_imageio_webp::register_importer(reg);
    // <ph2d-imageio-sync:importers:end>
}

/// Register every exporter with `reg`. Body codegen'd. Same rationale
/// as [`register_all_importers`]: dispatch is by
/// [`ph2d_imageio::ImageExporter::supports_format`] against
/// [`ph2d_imageio::ExportOpts::format`], not source order.
pub fn register_all_exporters(reg: &mut ExporterRegistry) {
    // <ph2d-imageio-sync:exporters:begin>
    ph2d_imageio_gif::register_exporter(reg);
    ph2d_imageio_jpeg::register_exporter(reg);
    ph2d_imageio_png::register_exporter(reg);
    ph2d_imageio_webp::register_exporter(reg);
    // <ph2d-imageio-sync:exporters:end>
}

#[cfg(test)]
mod tests {
    use super::*;
    use ph2d_imageio::MagicHint;

    #[test]
    fn register_all_importers_wires_png_at_minimum() {
        // PNG is the W0.T5 floor — must always be wired. The count
        // grows with every W1+ format crate; assert presence by
        // extension so the test scales with the fan-out without
        // edits.
        let mut reg = ImporterRegistry::new();
        register_all_importers(&mut reg);
        assert!(!reg.is_empty(), "at least one importer should be wired");
        assert!(
            reg.find_for(MagicHint::Extension("png")).is_some(),
            "PNG importer must be findable (W0.T5 floor)"
        );
    }

    #[test]
    fn register_all_exporters_wires_png_at_minimum() {
        let mut reg = ExporterRegistry::new();
        register_all_exporters(&mut reg);
        assert!(!reg.is_empty(), "at least one exporter should be wired");
    }
}
