//! Widget primitives. Each follows the Button pattern: data struct +
//! state enum + token-resolved colors + AccessKit Node builder + a
//! `paint_X` helper colocated in the widget file (not paint.rs —
//! keeps paint.rs as the dispatch layer for compound widgets like
//! FloatingPanel and ToastQueue).
//!
//! ## Wave 10 / Etapa 4.3 — `mod` declarations are codegen'd
//!
//! The block between `// <ph2d-widget-sync:begin>` and
//! `// <ph2d-widget-sync:end>` is regenerated by
//! `cargo run -p ph2d-widget-sync` from a scan of this directory.
//! The `pub use ...` re-exports below stay hand-written (per-widget
//! export shapes vary). Staleness gate in `tests/architecture_widget_mod_in_sync.rs`.

// <ph2d-widget-sync:begin>
mod avatar;
mod bitmask_grid32;
mod blender_color_picker;
mod button;
mod card;
mod checkbox;
mod color_picker;
mod color_swatch;
mod combobox;
mod context_menu;
mod divider;
mod dropdown;
mod icon_button;
mod key_value_list;
mod level_meter;
mod list_item;
mod modal;
mod number_input;
mod numeric_input_with_unit;
pub mod panel_chrome;
mod pill_group;
mod popover;
mod progress_bar;
mod radio_group;
mod rect2_editor;
mod scrollbar;
mod section_header;
mod segmented_adaptive;
pub mod showcase;
mod slider;
mod slider_with_chip;
mod spinner;
mod status_bar;
mod tabs;
mod tag;
mod text_area;
mod text_input;
mod toggle;
mod tool_rail;
mod tooltip;
mod tree_view;
mod variant_editor;
mod vector3_editor;
// <ph2d-widget-sync:end>

pub use avatar::{Avatar, AvatarShape, AvatarState, paint_avatar};
pub use bitmask_grid32::{BITMASK_COLS, BITMASK_ROWS, BitmaskGrid32, paint_bitmask_grid32};
pub use blender_color_picker::{
    BlenderColorPicker, BlenderSubIds, ChannelMode, ColorPalette, InterpolationMode,
    apply_blender_value_pick, apply_blender_wheel_pick, default_palette, hsv_to_rgba8,
    oklch_norm_channels, oklch_set_channel, paint_blender_color_picker,
    paint_blender_color_picker_with_store, paint_blender_color_picker_with_store_compat, parse_hex,
    rgba_to_hsv, value_pick, wheel_pick,
};
pub use button::{
    Button, ButtonKind, ButtonState, ICON_BUTTON_SIZE_PX, flat_button_surface, paint_button,
};
pub use card::{Card, paint_card, pop_card_body_clip, push_card_body_clip};
pub use checkbox::{CHECKBOX_BOX_PX, Checkbox, CheckboxState, CheckboxValue, paint_checkbox};
pub use color_picker::{ColorPicker, ColorPickerMode, paint_color_picker};
pub use color_swatch::{ColorSwatch, SwatchSize, SwatchState, paint_color_swatch};
pub use combobox::{
    Combobox, ComboboxOption, ComboboxState, paint_combobox, paint_combobox_with_state,
};
pub use context_menu::{ContextMenu, ContextMenuEntry, paint_context_menu};
pub use divider::{Divider, DividerOrientation, paint_divider};
pub use dropdown::{
    DROPDOWN_SCROLLBAR_ID, Dropdown, DropdownOption, DropdownState, paint_dropdown,
    paint_dropdown_chip, paint_dropdown_popover, paint_dropdown_popover_in_viewport,
    paint_dropdown_popover_scrolled,
};
pub use icon_button::{IconButtonStyle, IconGlyph, paint_icon_button};
pub use key_value_list::{KeyValueEntry, KeyValueList, paint_key_value_list};
pub use level_meter::{LevelMeter, paint_level_meter};
pub use list_item::{ListItem, ListItemState, paint_list_item};
pub use modal::{Modal, paint_modal, pop_modal_body_clip, push_modal_body_clip};
pub use number_input::{
    MIN_W_PX as NUMBER_INPUT_MIN_W_PX, NumberInput, paint_number_input,
    paint_number_input_with_buffer,
};
pub use numeric_input_with_unit::{
    NumericInputWithUnit, Unit, paint_numeric_input_with_unit, parse as parse_numeric_with_unit,
};
pub use pill_group::{PILL_PADDING_PX, PillGroup, paint_pill_group};
pub use popover::{Popover, anchor_below, paint_popover, pop_popover_clip, push_popover_clip};
pub use progress_bar::{ProgressBar, ProgressMode, paint_progress_bar};
pub use radio_group::{
    RadioGroup, RadioOption, RadioOrientation, paint_radio_group, paint_radio_group_with_labels,
};
pub use rect2_editor::{
    RECT2_HANDLE_COUNT, Rect2Editor, Rect2Layout, paint_rect2_editor,
    paint_rect2_editor_with_state, paint_rect2_handles,
};
pub use scrollbar::{
    AUDIO_EDITOR_SCROLLBAR_ID, AUDIO_MIXER_SCROLLBAR_ID, BG_REMOVAL_SCROLLBAR_ID,
    COLOR_EQUALIZATION_SCROLLBAR_ID, EQUALIZE_SIZES_SCROLLBAR_ID, GALLERY_SCROLLBAR_ID,
    GRID_SETTINGS_SCROLLBAR_ID, HIERARCHY_SCROLLBAR_ID, INSPECTOR_SCROLLBAR_ID,
    PADDING_SCROLLBAR_ID, PAINTER_BRUSH_STUDIO_SCROLLBAR_ID, PAINTER_LAYERS_SCROLLBAR_ID,
    SCROLLBAR_W, UPSCALE_SCROLLBAR_ID, VECTOR_SCROLLBAR_ID,
    delta_for_drag as scrollbar_delta_for_drag, is_needed as scrollbar_is_needed, paint_scrollbar,
    thumb_rect as scrollbar_thumb_rect, track_rect as scrollbar_track_rect,
};
pub use section_header::{SectionHeader, color_circle_hit_rect, paint_section_header};
pub use segmented_adaptive::{
    SegmentedAdaptive, SegmentedOption, measure_segmented_adaptive, paint_segmented_adaptive,
};
pub use slider::{Slider, SliderOrientation, SliderState, paint_slider, paint_slider_track};
pub use slider_with_chip::{
    DEFAULT_CHIP_W, DEFAULT_LABEL_W, paint_number_chip, paint_slider_with_chip,
    paint_slider_with_chip_layout, paint_slider_with_chip_layout_adaptive, slider_with_chip_height,
    slider_with_chip_is_stacked,
};
pub use spinner::{Spinner, paint_spinner};
pub use status_bar::{SegmentTone, StatusBar, StatusSegment, paint_status_bar};
pub use tabs::{TabItem, Tabs, TabsVariant, paint_tabs, paint_tabs_with_hover};
pub use tag::{Tag, TagState, TagTone, paint_tag};
pub use text_area::{
    TextArea, min_height as text_area_min_height, paint_text_area, paint_text_area_with_state,
};
pub use text_input::{TextInput, TextInputState, paint_text_input, paint_text_input_with_buffer};
pub use toggle::{Toggle, ToggleState, paint_toggle};
pub use tool_rail::{
    CHIP_X_OFFSET_PX, COMPOUND_TOTAL_H_PX, DIVIDER_GAP_PX, RailButtonSize, TOOL_CHIP_PX,
    TOOL_RAIL_WIDTH_PX, ToolRail, ToolRailEntry, paint_tool_rail,
};
pub use tooltip::{Tooltip, paint_tooltip};
pub use tree_view::{TreeNode, TreeView, paint_tree_view};
pub use variant_editor::{
    MAX_VARIANT_DEPTH, VariantEditor, VariantKind, VariantRow, VariantValue,
    flatten as flatten_variant, paint_variant_editor,
};
pub use vector3_editor::{Vector3Editor, paint_vector3_editor, paint_vector3_editor_with_state};
