//! The **Polygon** stroke method's geometry: a regular N-gon (3..=12 sides) inscribed in an ellipse,
//! and the spaced-dab fill along its perimeter. A child module of [`super`] (`stroke`) so it keeps
//! private access to `Stroke`'s walk internals; split out for the workspace LOC cap. See
//! `stroke_method::StrokeMethod::Polygon` — a PH2D shape extension.
//!
//! ## Why no `sin`/`cos`
//!
//! `sin`/`cos` are libm-dependent and NOT bit-reproducible across platforms (HR-5). The N vertices
//! are generated by INCREMENTAL ROTATION of a unit vector by the fixed step `2π/N`, whose
//! `(cos, sin)` is a BAKED CONSTANT ([`POLY_STEP`]) — so runtime touches only `*`/`+`. Orientation is
//! a unit VECTOR (never an angle). The accumulated rotation drift over ≤ 12 steps is sub-`1e-6` and
//! deterministic.

use super::*;

/// Smallest / largest side count the polygon editor allows.
pub const POLY_MIN_SIDES: u32 = 3;
/// See [`POLY_MIN_SIDES`].
pub const POLY_MAX_SIDES: u32 = 12;

/// Per-side rotation step `(cos(2π/n), sin(2π/n))`, indexed by side count `n` (valid `3..=12`;
/// indices `0..=2` are inert placeholders). Baked constants so vertex generation is transcendental-
/// free. Values are `f64`-accurate `cos`/`sin` of `2π/n`, rounded to `f32`.
const POLY_STEP: [(f32, f32); 13] = [
    (1.0, 0.0),                   // 0 (unused)
    (1.0, 0.0),                   // 1 (unused)
    (1.0, 0.0),                   // 2 (unused)
    (-0.5, 0.866_025_4),          // 3  (120°)
    (0.0, 1.0),                   // 4  (90°)
    (0.309_017, 0.951_056_5),     // 5  (72°)
    (0.5, 0.866_025_4),           // 6  (60°)
    (0.623_489_8, 0.781_831_5),   // 7  (≈51.43°)
    (0.707_106_77, 0.707_106_77), // 8 (45°)
    (0.766_044_4, 0.642_787_6),   // 9  (40°)
    (0.809_017, 0.587_785_25),    // 10 (36°)
    (0.841_253_5, 0.540_640_8),   // 11 (≈32.73°)
    (0.866_025_4, 0.5),           // 12 (30°)
];

impl Stroke {
    /// Fill the perimeter of the regular `sides`-gon (clamped `3..=12`) inscribed in the ellipse
    /// `(center, u, rx, ry)` with spaced dabs for the live preview. `u` is the local x-axis unit
    /// vector; the first vertex sits at the top (`+y` local). Lays dabs along the straight edges
    /// (gated by dash, with jitter) at constant full pressure, closing the loop. Fresh-per-fill +
    /// deterministic, like the other shape fills. `offset_px` insets/outsets the perimeter (Offset slider).
    /// A degenerate (`< 0.5 px` either axis) shape fills nothing.
    #[allow(clippy::too_many_arguments)]
    pub fn fill_polygon_preview(
        &mut self,
        center: [f32; 2],
        u: [f32; 2],
        rx: f32,
        ry: f32,
        sides: u32,
        offset_px: f32,
        out: &mut Vec<Dab>,
    ) {
        out.clear();
        if rx < 0.5 || ry < 0.5 {
            return;
        }
        let mut perim = Vec::new();
        polygon_perimeter(center, u, rx, ry, sides, &mut perim);
        if offset_px != 0.0 {
            perim = super::offset::offset_polyline(&perim, offset_px, true); // closed loop
        }
        if perim.len() < 2 {
            return;
        }
        self.last_pos = perim[0];
        self.last_pressure = 1.0;
        self.accum = 0.0;
        self.tot_samples = 0;
        self.heading = [0.0, 0.0]; // fresh fill → the Rake heading re-aims along the perimeter from the start
        if self.spec.dash_on(self.tot_samples) {
            let pr = self.method_pressure(1.0);
            let d = self.dab_at(perim[0], pr, self.method_overlap());
            out.push(d);
        }
        self.tot_samples = self.tot_samples.wrapping_add(1);
        for &p in &perim[1..] {
            self.walk_space(
                StrokePoint {
                    pos: p,
                    pressure: 1.0,
                },
                out,
            );
        }
        // Close the loop back to the first vertex.
        self.walk_space(
            StrokePoint {
                pos: perim[0],
                pressure: 1.0,
            },
            out,
        );
    }
}

/// Generate the `sides` vertices (clamped `3..=12`) of the regular polygon inscribed in the ellipse
/// `(center, u, rx, ry)`, written to `out` (cleared first; the loop is NOT closed — the caller walks
/// back to `out[0]`). `u` is the local x-axis unit vector; the first vertex is at the top (`+y`).
/// Transcendental-free (module header): a unit vertex is rotated by the baked `2π/n` step.
///
/// Shared by [`Stroke::fill_polygon_preview`] (the painted dabs) and the tool's editor overlay (the
/// drawn outline), so the on-screen guide matches the dabs exactly.
pub fn polygon_perimeter(
    center: [f32; 2],
    u: [f32; 2],
    rx: f32,
    ry: f32,
    sides: u32,
    out: &mut Vec<[f32; 2]>,
) {
    out.clear();
    let n = sides.clamp(POLY_MIN_SIDES, POLY_MAX_SIDES);
    let (cs, sn) = POLY_STEP[n as usize];
    let un = unit_or(u, [1.0, 0.0]); // local x-axis (orientation)
    let v = [-un[1], un[0]]; // local y-axis (left perpendicular)
    // First vertex at the top (local `+y`), so triangles/pentagons point up.
    let (mut cx, mut cy) = (0.0f32, 1.0f32);
    out.reserve(n as usize);
    for _ in 0..n {
        out.push([
            center[0] + rx * cx * un[0] + ry * cy * v[0],
            center[1] + rx * cx * un[1] + ry * cy * v[1],
        ]);
        // Rotate the unit vertex by the baked step (CCW): (cx, cy) ← R(2π/n)·(cx, cy).
        let nx = cx * cs - cy * sn;
        let ny = cx * sn + cy * cs;
        cx = nx;
        cy = ny;
    }
}

/// Normalize `p`, falling back to `fallback` for a (near) zero vector. Only `sqrt` (deterministic).
fn unit_or(p: [f32; 2], fallback: [f32; 2]) -> [f32; 2] {
    let len = (p[0] * p[0] + p[1] * p[1]).sqrt();
    if len > 1e-6 {
        [p[0] / len, p[1] / len]
    } else {
        fallback
    }
}
