//! `NodeId`s dos widgets do painel da cena 3D.
//!
//! Como em todo crate de painel, os ids continuam definidos na editor-core
//! (`ph2d_editor_core::ids`) — o layout, o walk de z-order e o arch-test
//! `node_id_collisions` os referenciam, e redefini-los aqui bifurcaria a fonte
//! da verdade. Isto é um re-export de conveniência.

pub use ph2d_editor_core::ids::{
    SCULPT3D_ADD, SCULPT3D_CAVITY, SCULPT3D_CAVITY_NUM, SCULPT3D_CLOSE, SCULPT3D_CLOSE_HOLES,
    SCULPT3D_DELETE, SCULPT3D_DETAIL, SCULPT3D_DUPLICATE, SCULPT3D_DYNTOPO, SCULPT3D_FALLOFF,
    SCULPT3D_ISOLATE, SCULPT3D_LEVEL_DOWN, SCULPT3D_LEVEL_UP, SCULPT3D_LIGHT_AZ,
    SCULPT3D_LIGHT_AZ_NUM, SCULPT3D_LIGHT_ELEV, SCULPT3D_LIGHT_ELEV_NUM, SCULPT3D_MASK_OP,
    SCULPT3D_MERGE, SCULPT3D_PANEL, SCULPT3D_PINCH, SCULPT3D_PINCH_NUM, SCULPT3D_PLANE_OFFSET,
    SCULPT3D_PLANE_OFFSET_NUM, SCULPT3D_RADIUS, SCULPT3D_RADIUS_NUM, SCULPT3D_REMESH,
    SCULPT3D_REVERSE, SCULPT3D_SEC_BRUSH, SCULPT3D_SEC_SCENE, SCULPT3D_SEC_SHADING,
    SCULPT3D_SEC_SYMMETRY, SCULPT3D_SEC_TOOL, SCULPT3D_SEC_TOPOLOGY, SCULPT3D_STRENGTH,
    SCULPT3D_STRENGTH_NUM, SCULPT3D_SUBDIVIDE, SCULPT3D_SYM_X, SCULPT3D_SYM_Y, SCULPT3D_SYM_Z,
    SCULPT3D_VERB,
};
