[package]
name = "ph2d-node-motion-combine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[lib]

[dependencies]
ph2d-nodegraph = { path = "../ph2d-nodegraph" }
ph2d-node-registry = { path = "../ph2d-node-registry" }
